// Biomarker knowledge base — curated reference data
// Sources: standard clinical laboratory references

import type { BiomarkerKnowledge } from './types';

function kb(data: BiomarkerKnowledge): BiomarkerKnowledge {
  return data;
}

const BIOMARKER_LIST: BiomarkerKnowledge[] = [
  kb({
    code: 'HGB',
    name: 'Hemoglobin',
    aliases: ['Hgb', 'Hb', 'Hemoglobin'],
    category: 'hematology',
    specimenType: 'whole blood',
    defaultUnit: 'g/dL',
    alternativeUnits: ['g/L'],
    referenceRanges: [
      { sex: 'male', min: 13.5, max: 17.5, unit: 'g/dL', source: 'WHO/CLSI' },
      { sex: 'female', min: 12.0, max: 15.5, unit: 'g/dL', source: 'WHO/CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 7.0, unit: 'g/dL', severity: 'critical', message: 'Critically low hemoglobin — may require urgent transfusion.', action: 'Seek immediate medical attention.' },
      { direction: 'low', value: 10.0, unit: 'g/dL', severity: 'warning', message: 'Low hemoglobin — moderate anemia.', action: 'Contact your healthcare provider soon.' },
      { direction: 'high', value: 20.0, unit: 'g/dL', severity: 'critical', message: 'Critically high hemoglobin — risk of hyperviscosity.', action: 'Seek immediate medical attention.' },
    ],
    whatItMeasures: 'The oxygen-carrying protein in red blood cells.',
    whatResultMayMean: { high: 'May indicate dehydration, polycythemia, or chronic hypoxia.', low: 'May indicate anemia from iron deficiency, chronic disease, or blood loss.' },
    commonNonDangerousReasons: { high: ['Dehydration', 'High altitude living', 'Intense exercise'], low: ['Menstruation', 'Mild dietary iron insufficiency', 'Pregnancy'] },
    whenItMatters: 'Persistent abnormalities or symptoms like fatigue, pallor, or shortness of breath.',
    dailyLifeActions: { high: ['Stay hydrated', 'Avoid smoking'], low: ['Eat iron-rich foods', 'Pair iron with vitamin C', 'Avoid coffee/tea with meals'] },
    whenToSeeDoctor: { high: 'Persistent elevation above 18 g/dL or symptoms like headaches and dizziness.', low: 'Persistent fatigue, pallor, or values below 10 g/dL.' },
    preAnalyticalConfounders: ['Dehydration concentrates blood', 'Overhydration dilutes it', 'Tourniquet time'],
    medicationsAffecting: ['Erythropoietin', 'Chemotherapy', 'Antiretrovirals'],
    relatedBiomarkers: ['HCT', 'RBC', 'MCV', 'FERRITIN'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'HCT',
    name: 'Hematocrit',
    aliases: ['Hct', 'PCV', 'Packed Cell Volume'],
    category: 'hematology',
    specimenType: 'whole blood',
    defaultUnit: '%',
    referenceRanges: [
      { sex: 'male', min: 38.3, max: 48.6, unit: '%', source: 'CLSI' },
      { sex: 'female', min: 35.5, max: 44.9, unit: '%', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 20, unit: '%', severity: 'critical', message: 'Critically low hematocrit.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 60, unit: '%', severity: 'critical', message: 'Critically high hematocrit — hyperviscosity risk.', action: 'Seek immediate medical attention.' },
    ],
    whatItMeasures: 'The percentage of blood volume occupied by red blood cells.',
    whatResultMayMean: { high: 'May indicate dehydration, polycythemia, or chronic lung disease.', low: 'May indicate anemia, blood loss, or overhydration.' },
    commonNonDangerousReasons: { high: ['Dehydration', 'High altitude'], low: ['Overhydration', 'Mild anemia'] },
    whenItMatters: 'When evaluating anemia, dehydration, or polycythemia.',
    dailyLifeActions: { high: ['Stay well hydrated'], low: ['Address underlying anemia causes'] },
    whenToSeeDoctor: { high: 'Values above 55% or symptoms of blood thickening.', low: 'Values below 25% or persistent fatigue.' },
    preAnalyticalConfounders: ['Dehydration', 'Posture during collection'],
    medicationsAffecting: ['Erythropoietin', 'Diuretics'],
    relatedBiomarkers: ['HGB', 'RBC', 'MCV'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'RBC',
    name: 'Red Blood Cell Count',
    aliases: ['RBC', 'Erythrocytes', 'Red Cell Count'],
    category: 'hematology',
    specimenType: 'whole blood',
    defaultUnit: '10^6/µL',
    referenceRanges: [
      { sex: 'male', min: 4.5, max: 5.5, unit: '10^6/µL', source: 'CLSI' },
      { sex: 'female', min: 3.9, max: 5.0, unit: '10^6/µL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 2.5, unit: '10^6/µL', severity: 'critical', message: 'Critically low RBC count.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 7.0, unit: '10^6/µL', severity: 'warning', message: 'Significantly elevated RBC count.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'The number of red blood cells per unit of blood.',
    whatResultMayMean: { high: 'May indicate polycythemia, dehydration, or chronic hypoxia.', low: 'May indicate anemia, blood loss, or bone marrow issues.' },
    commonNonDangerousReasons: { high: ['Dehydration', 'High altitude'], low: ['Mild iron deficiency', 'Menstruation'] },
    whenItMatters: 'When evaluating blood production and oxygen delivery.',
    dailyLifeActions: { high: ['Stay hydrated'], low: ['Iron-rich diet', 'Adequate nutrition'] },
    whenToSeeDoctor: { high: 'Persistent elevation with symptoms.', low: 'Persistent low counts or worsening fatigue.' },
    preAnalyticalConfounders: ['Dehydration', 'Time of day'],
    medicationsAffecting: ['Erythropoietin', 'Chemotherapy'],
    relatedBiomarkers: ['HGB', 'HCT', 'MCV'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'WBC',
    name: 'White Blood Cell Count',
    aliases: ['WBC', 'Leukocytes', 'White Count'],
    category: 'hematology',
    specimenType: 'whole blood',
    defaultUnit: '10^3/µL',
    referenceRanges: [
      { sex: 'any', min: 4.5, max: 11.0, unit: '10^3/µL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 30.0, unit: '10^3/µL', severity: 'critical', message: 'Very high WBC — possible severe infection or hematologic condition.', action: 'Seek immediate medical attention.' },
      { direction: 'low', value: 2.0, unit: '10^3/µL', severity: 'critical', message: 'Critically low WBC — high infection risk.', action: 'Seek immediate medical attention.' },
    ],
    whatItMeasures: 'The total number of white blood cells, the body\'s immune defense cells.',
    whatResultMayMean: { high: 'May indicate infection, inflammation, stress, or blood disorders.', low: 'May indicate bone marrow suppression, viral infection, or autoimmune conditions.' },
    commonNonDangerousReasons: { high: ['Acute stress', 'Strenuous exercise', 'Smoking'], low: ['Viral infections', 'Some medications'] },
    whenItMatters: 'When evaluating immune function or investigating infection.',
    dailyLifeActions: { high: ['Rest if acutely ill', 'Stay hydrated'], low: ['Good hygiene', 'Avoid sick contacts'] },
    whenToSeeDoctor: { high: 'Persistent elevation or values above 20,000.', low: 'Values below 3,000 or recurrent infections.' },
    preAnalyticalConfounders: ['Exercise', 'Stress', 'Time of day', 'Smoking'],
    medicationsAffecting: ['Corticosteroids', 'Chemotherapy', 'Lithium'],
    relatedBiomarkers: ['NEUTROPHILS', 'CRP', 'ESR'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'MCV',
    name: 'Mean Corpuscular Volume',
    aliases: ['MCV'],
    category: 'hematology',
    specimenType: 'whole blood',
    defaultUnit: 'fL',
    referenceRanges: [
      { sex: 'any', min: 80, max: 100, unit: 'fL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 60, unit: 'fL', severity: 'warning', message: 'Very low MCV — suggests significant microcytic anemia.', action: 'Contact your healthcare provider.' },
      { direction: 'high', value: 115, unit: 'fL', severity: 'warning', message: 'Very high MCV — suggests significant macrocytic anemia.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'The average size of red blood cells.',
    whatResultMayMean: { high: 'May indicate B12/folate deficiency, liver disease, or hypothyroidism.', low: 'May indicate iron deficiency or thalassemia.' },
    commonNonDangerousReasons: { high: ['Moderate alcohol intake', 'Reticulocytosis'], low: ['Mild iron deficiency'] },
    whenItMatters: 'When classifying the type of anemia.',
    dailyLifeActions: { high: ['Ensure adequate B12 and folate', 'Moderate alcohol'], low: ['Iron-rich foods', 'Vitamin C with meals'] },
    whenToSeeDoctor: { high: 'Persistent elevation above 105 fL.', low: 'Persistent values below 75 fL.' },
    preAnalyticalConfounders: ['Sample age', 'Hyperglycemia can cause swelling'],
    medicationsAffecting: ['Methotrexate', 'Hydroxyurea', 'Antiretrovirals'],
    relatedBiomarkers: ['HGB', 'RBC', 'FERRITIN', 'B12', 'FOLATE'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'NEUTROPHILS',
    name: 'Neutrophils',
    aliases: ['Neut', 'Neutrophil Count', 'ANC'],
    category: 'hematology',
    specimenType: 'whole blood',
    defaultUnit: '10^3/µL',
    referenceRanges: [
      { sex: 'any', min: 1.8, max: 7.7, unit: '10^3/µL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 0.5, unit: '10^3/µL', severity: 'critical', message: 'Severe neutropenia — very high infection risk.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 20.0, unit: '10^3/µL', severity: 'warning', message: 'Very high neutrophils — possible severe infection.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'The most abundant white blood cell type, first responders to bacterial infection.',
    whatResultMayMean: { high: 'May indicate bacterial infection, inflammation, or stress response.', low: 'May indicate bone marrow suppression, viral infection, or autoimmune conditions.' },
    commonNonDangerousReasons: { high: ['Acute stress', 'Exercise', 'Smoking'], low: ['Benign ethnic neutropenia', 'Some viral infections'] },
    whenItMatters: 'When evaluating infection risk or inflammatory conditions.',
    dailyLifeActions: { high: ['Rest if ill'], low: ['Good hygiene', 'Avoid raw foods if severely low'] },
    whenToSeeDoctor: { high: 'Persistent elevation with fever.', low: 'Values below 1.0 or recurrent infections.' },
    preAnalyticalConfounders: ['Exercise', 'Stress', 'Diurnal variation'],
    medicationsAffecting: ['Corticosteroids', 'Chemotherapy', 'G-CSF'],
    relatedBiomarkers: ['WBC', 'CRP'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'GLUCOSE',
    name: 'Fasting Glucose',
    aliases: ['Blood Sugar', 'FBG', 'Fasting Blood Glucose', 'Glucose'],
    category: 'metabolic',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 70, max: 99, unit: 'mg/dL', source: 'ADA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 400, unit: 'mg/dL', severity: 'critical', message: 'Dangerously high glucose — risk of diabetic emergency.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 126, unit: 'mg/dL', severity: 'warning', message: 'Fasting glucose in diabetic range.', action: 'Contact your healthcare provider for HbA1c testing.' },
      { direction: 'low', value: 50, unit: 'mg/dL', severity: 'critical', message: 'Critically low glucose — hypoglycemia.', action: 'Consume fast-acting sugar immediately. Seek medical attention if symptoms persist.' },
    ],
    whatItMeasures: 'The amount of sugar (glucose) in the blood after fasting.',
    whatResultMayMean: { high: 'May indicate pre-diabetes, diabetes, or stress response.', low: 'May indicate hypoglycemia from fasting, medication, or rare conditions.' },
    commonNonDangerousReasons: { high: ['Recent meal (non-fasting sample)', 'Acute stress', 'Medications (corticosteroids)'], low: ['Prolonged fasting', 'Intense exercise'] },
    whenItMatters: 'Consistently elevated fasting glucose warrants diabetes screening.',
    dailyLifeActions: { high: ['Reduce refined carbs', 'Increase fiber', 'Regular exercise', 'Healthy weight'], low: ['Regular meals', 'Include protein with carbs'] },
    whenToSeeDoctor: { high: 'Fasting glucose consistently above 100 mg/dL.', low: 'Recurrent hypoglycemic symptoms.' },
    preAnalyticalConfounders: ['Fasting status', 'Stress', 'Time of day', 'Recent exercise'],
    medicationsAffecting: ['Corticosteroids', 'Thiazide diuretics', 'Beta-blockers', 'Insulin', 'Metformin'],
    relatedBiomarkers: ['HBA1C', 'TRIGLYCERIDES', 'HDL'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'HBA1C',
    name: 'Hemoglobin A1c',
    aliases: ['HbA1c', 'A1C', 'Glycated Hemoglobin', 'Glycosylated Hemoglobin'],
    category: 'metabolic',
    specimenType: 'whole blood',
    defaultUnit: '%',
    alternativeUnits: ['mmol/mol'],
    referenceRanges: [
      { sex: 'any', min: 4.0, max: 5.6, unit: '%', source: 'ADA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 10.0, unit: '%', severity: 'critical', message: 'Very high HbA1c — poorly controlled diabetes.', action: 'Contact your healthcare provider urgently.' },
      { direction: 'high', value: 6.5, unit: '%', severity: 'warning', message: 'HbA1c in diabetic range.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'Average blood sugar level over the past 2-3 months.',
    whatResultMayMean: { high: 'May indicate pre-diabetes (5.7-6.4%) or diabetes (>=6.5%).', low: 'May indicate frequent hypoglycemia or conditions affecting RBC lifespan.' },
    commonNonDangerousReasons: { high: ['Dietary patterns', 'Sedentary lifestyle'], low: ['Iron deficiency (can falsely lower)', 'Hemolytic conditions'] },
    whenItMatters: 'Gold standard for diabetes diagnosis and monitoring.',
    dailyLifeActions: { high: ['Low glycemic diet', 'Regular exercise', 'Weight management'], low: ['Adequate caloric intake'] },
    whenToSeeDoctor: { high: 'HbA1c above 5.7%.', low: 'Unexpectedly low values in diabetic patients.' },
    preAnalyticalConfounders: ['Hemoglobin variants', 'Iron deficiency', 'Recent transfusion'],
    medicationsAffecting: ['Insulin', 'Metformin', 'Dapsone'],
    relatedBiomarkers: ['GLUCOSE', 'TRIGLYCERIDES'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'TOTAL_CHOLESTEROL',
    name: 'Total Cholesterol',
    aliases: ['TC', 'Cholesterol', 'Total Chol'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: null, max: 200, unit: 'mg/dL', source: 'ATP III/ACC-AHA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 300, unit: 'mg/dL', severity: 'warning', message: 'Very high total cholesterol.', action: 'Contact your healthcare provider for lipid management.' },
    ],
    whatItMeasures: 'Total amount of cholesterol in the blood (LDL + HDL + VLDL).',
    whatResultMayMean: { high: 'May indicate increased cardiovascular risk.', low: 'May indicate malnutrition, liver disease, or hyperthyroidism.' },
    commonNonDangerousReasons: { high: ['Diet high in saturated fat', 'Genetic predisposition'], low: ['Very low-fat diet'] },
    whenItMatters: 'As part of cardiovascular risk assessment.',
    dailyLifeActions: { high: ['Reduce saturated fats', 'Increase fiber', 'Exercise regularly'], low: ['Balanced diet with healthy fats'] },
    whenToSeeDoctor: { high: 'Values above 240 mg/dL.', low: 'Values below 120 mg/dL without explanation.' },
    preAnalyticalConfounders: ['Fasting status', 'Posture', 'Recent illness'],
    medicationsAffecting: ['Statins', 'Fibrates', 'Oral contraceptives', 'Corticosteroids'],
    relatedBiomarkers: ['LDL', 'HDL', 'TRIGLYCERIDES'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'LDL',
    name: 'LDL Cholesterol',
    aliases: ['LDL-C', 'Low-Density Lipoprotein', 'Bad Cholesterol'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: null, max: 100, unit: 'mg/dL', source: 'ACC-AHA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 190, unit: 'mg/dL', severity: 'warning', message: 'Very high LDL — may indicate familial hypercholesterolemia.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'The amount of LDL ("bad") cholesterol that deposits in artery walls.',
    whatResultMayMean: { high: 'May indicate increased atherosclerosis and cardiovascular risk.', low: 'Generally favorable; very low values are usually not concerning.' },
    commonNonDangerousReasons: { high: ['Diet', 'Genetics', 'Sedentary lifestyle'], low: ['Statin use', 'Very active lifestyle'] },
    whenItMatters: 'Primary target for cardiovascular risk reduction.',
    dailyLifeActions: { high: ['Reduce saturated fat', 'Increase soluble fiber', 'Exercise', 'Plant sterols'], low: [] },
    whenToSeeDoctor: { high: 'Values above 130 mg/dL (or lower targets if high-risk).', low: 'Generally not a concern.' },
    preAnalyticalConfounders: ['Fasting status', 'Method of calculation vs direct measurement'],
    medicationsAffecting: ['Statins', 'PCSK9 inhibitors', 'Ezetimibe'],
    relatedBiomarkers: ['TOTAL_CHOLESTEROL', 'HDL', 'TRIGLYCERIDES'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'HDL',
    name: 'HDL Cholesterol',
    aliases: ['HDL-C', 'High-Density Lipoprotein', 'Good Cholesterol'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'male', min: 40, max: null, unit: 'mg/dL', source: 'ACC-AHA' },
      { sex: 'female', min: 50, max: null, unit: 'mg/dL', source: 'ACC-AHA' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 25, unit: 'mg/dL', severity: 'warning', message: 'Very low HDL — significant cardiovascular risk factor.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'The amount of HDL ("good") cholesterol that removes cholesterol from arteries.',
    whatResultMayMean: { high: 'Generally protective; very high values rarely concerning.', low: 'May indicate increased cardiovascular risk.' },
    commonNonDangerousReasons: { high: ['Regular exercise', 'Moderate alcohol', 'Genetics'], low: ['Sedentary lifestyle', 'Smoking', 'Obesity'] },
    whenItMatters: 'As part of cardiovascular risk assessment.',
    dailyLifeActions: { high: ['Continue healthy habits'], low: ['Regular aerobic exercise', 'Quit smoking', 'Healthy fats', 'Weight loss if applicable'] },
    whenToSeeDoctor: { high: 'Usually not concerning.', low: 'Values below 40 mg/dL (men) or 50 mg/dL (women).' },
    preAnalyticalConfounders: ['Fasting status', 'Acute illness lowers HDL'],
    medicationsAffecting: ['Statins', 'Niacin', 'Fibrates'],
    relatedBiomarkers: ['TOTAL_CHOLESTEROL', 'LDL', 'TRIGLYCERIDES'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'TRIGLYCERIDES',
    name: 'Triglycerides',
    aliases: ['TG', 'Trig', 'Trigs'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: null, max: 150, unit: 'mg/dL', source: 'ACC-AHA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 500, unit: 'mg/dL', severity: 'critical', message: 'Very high triglycerides — risk of pancreatitis.', action: 'Seek medical attention promptly.' },
      { direction: 'high', value: 200, unit: 'mg/dL', severity: 'warning', message: 'Elevated triglycerides.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'The amount of fat (triglycerides) circulating in the blood.',
    whatResultMayMean: { high: 'May indicate metabolic syndrome, insulin resistance, or high-carb diet.', low: 'Generally favorable.' },
    commonNonDangerousReasons: { high: ['Recent meal', 'High-carb diet', 'Alcohol'], low: ['Low-fat diet', 'Very active lifestyle'] },
    whenItMatters: 'When assessing cardiovascular and metabolic risk.',
    dailyLifeActions: { high: ['Reduce sugar and refined carbs', 'Limit alcohol', 'Omega-3 fatty acids', 'Exercise'], low: [] },
    whenToSeeDoctor: { high: 'Values above 200 mg/dL or above 500 urgently.', low: 'Generally not a concern.' },
    preAnalyticalConfounders: ['Must be fasting (12 hours)', 'Alcohol within 24 hours'],
    medicationsAffecting: ['Fibrates', 'Omega-3 supplements', 'Statins', 'Corticosteroids'],
    relatedBiomarkers: ['GLUCOSE', 'HBA1C', 'HDL'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'ALT',
    name: 'Alanine Aminotransferase',
    aliases: ['ALT', 'SGPT', 'Alanine Transaminase'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'U/L',
    referenceRanges: [
      { sex: 'male', min: 7, max: 56, unit: 'U/L', source: 'AASLD' },
      { sex: 'female', min: 7, max: 45, unit: 'U/L', source: 'AASLD' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 1000, unit: 'U/L', severity: 'critical', message: 'Severely elevated ALT — acute liver injury.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 200, unit: 'U/L', severity: 'warning', message: 'Significantly elevated ALT.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'A liver enzyme released into the blood when liver cells are damaged.',
    whatResultMayMean: { high: 'May indicate liver inflammation, fatty liver, hepatitis, or medication effects.', low: 'Usually not clinically significant.' },
    commonNonDangerousReasons: { high: ['Intense exercise', 'Acetaminophen use', 'Mild fatty liver'], low: [] },
    whenItMatters: 'Persistent elevation warrants liver evaluation.',
    dailyLifeActions: { high: ['Limit alcohol', 'Maintain healthy weight', 'Review medications', 'Exercise regularly'], low: [] },
    whenToSeeDoctor: { high: 'ALT above 2x normal or persistent elevation.', low: 'Usually not needed.' },
    preAnalyticalConfounders: ['Intense exercise', 'Hemolysis of sample'],
    medicationsAffecting: ['Acetaminophen', 'Statins', 'NSAIDs', 'Antibiotics'],
    relatedBiomarkers: ['AST', 'GGT', 'BILIRUBIN', 'ALBUMIN'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'AST',
    name: 'Aspartate Aminotransferase',
    aliases: ['AST', 'SGOT', 'Aspartate Transaminase'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'U/L',
    referenceRanges: [
      { sex: 'male', min: 10, max: 40, unit: 'U/L', source: 'CLSI' },
      { sex: 'female', min: 9, max: 32, unit: 'U/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 1000, unit: 'U/L', severity: 'critical', message: 'Severely elevated AST — acute liver or muscle injury.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 200, unit: 'U/L', severity: 'warning', message: 'Significantly elevated AST.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'An enzyme found in liver, heart, and muscle cells. Released when these cells are damaged.',
    whatResultMayMean: { high: 'May indicate liver damage, muscle injury, or heart conditions.', low: 'Usually not clinically significant.' },
    commonNonDangerousReasons: { high: ['Intense exercise', 'Muscle strain'], low: [] },
    whenItMatters: 'When evaluating liver or muscle damage, especially alongside ALT.',
    dailyLifeActions: { high: ['Limit alcohol', 'Avoid overtraining', 'Review supplements'], low: [] },
    whenToSeeDoctor: { high: 'Persistent elevation or AST > 2x normal.', low: 'Usually not needed.' },
    preAnalyticalConfounders: ['Intense exercise', 'Hemolysis', 'Muscle trauma'],
    medicationsAffecting: ['Acetaminophen', 'Statins', 'Antibiotics'],
    relatedBiomarkers: ['ALT', 'GGT', 'BILIRUBIN'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'GGT',
    name: 'Gamma-Glutamyl Transferase',
    aliases: ['GGT', 'Gamma GT', 'GGTP'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'U/L',
    referenceRanges: [
      { sex: 'male', min: 8, max: 61, unit: 'U/L', source: 'CLSI' },
      { sex: 'female', min: 5, max: 36, unit: 'U/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 500, unit: 'U/L', severity: 'warning', message: 'Very high GGT — possible bile duct obstruction or significant liver disease.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'A liver enzyme particularly sensitive to alcohol and bile duct issues.',
    whatResultMayMean: { high: 'May indicate alcohol use, bile duct obstruction, liver disease, or medication effects.', low: 'Usually not clinically significant.' },
    commonNonDangerousReasons: { high: ['Alcohol consumption', 'Enzyme-inducing medications'], low: [] },
    whenItMatters: 'Helpful in distinguishing liver vs bone causes of elevated alkaline phosphatase.',
    dailyLifeActions: { high: ['Reduce or eliminate alcohol', 'Review medications'], low: [] },
    whenToSeeDoctor: { high: 'Persistent elevation, especially with other liver enzymes.', low: 'Usually not needed.' },
    preAnalyticalConfounders: ['Alcohol within 24 hours', 'Medications'],
    medicationsAffecting: ['Phenytoin', 'Barbiturates', 'Alcohol'],
    relatedBiomarkers: ['ALT', 'AST', 'BILIRUBIN'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'BILIRUBIN',
    name: 'Total Bilirubin',
    aliases: ['Bilirubin', 'TBIL', 'Total Bili'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['µmol/L'],
    referenceRanges: [
      { sex: 'any', min: 0.1, max: 1.2, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 5.0, unit: 'mg/dL', severity: 'critical', message: 'Very high bilirubin — jaundice likely.', action: 'Seek medical attention promptly.' },
      { direction: 'high', value: 2.0, unit: 'mg/dL', severity: 'warning', message: 'Elevated bilirubin.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'A yellow pigment formed from the breakdown of red blood cells, processed by the liver.',
    whatResultMayMean: { high: 'May indicate liver disease, bile duct obstruction, or hemolysis.', low: 'Usually not clinically significant.' },
    commonNonDangerousReasons: { high: ['Gilbert syndrome (common, harmless)', 'Fasting', 'Dehydration'], low: [] },
    whenItMatters: 'When evaluating jaundice or liver function.',
    dailyLifeActions: { high: ['Stay hydrated', 'Limit alcohol'], low: [] },
    whenToSeeDoctor: { high: 'Visible jaundice or values above 2.0 mg/dL.', low: 'Usually not needed.' },
    preAnalyticalConfounders: ['Light exposure degrades bilirubin', 'Fasting raises it slightly'],
    medicationsAffecting: ['Atazanavir', 'Some antibiotics'],
    relatedBiomarkers: ['ALT', 'AST', 'GGT', 'ALBUMIN'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'CREATININE',
    name: 'Creatinine',
    aliases: ['Creat', 'Cr', 'Serum Creatinine'],
    category: 'kidney',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['µmol/L'],
    referenceRanges: [
      { sex: 'male', min: 0.7, max: 1.3, unit: 'mg/dL', source: 'KDIGO' },
      { sex: 'female', min: 0.6, max: 1.1, unit: 'mg/dL', source: 'KDIGO' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 4.0, unit: 'mg/dL', severity: 'critical', message: 'Severely elevated creatinine — possible acute kidney injury.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 2.0, unit: 'mg/dL', severity: 'warning', message: 'Significantly elevated creatinine.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'A waste product from muscle metabolism, filtered by the kidneys.',
    whatResultMayMean: { high: 'May indicate reduced kidney function, dehydration, or high muscle mass.', low: 'May indicate low muscle mass; usually not concerning.' },
    commonNonDangerousReasons: { high: ['High-protein diet', 'Intense exercise', 'High muscle mass', 'Creatine supplementation'], low: ['Low muscle mass', 'Smaller body frame'] },
    whenItMatters: 'When assessing kidney function, especially with eGFR.',
    dailyLifeActions: { high: ['Stay hydrated', 'Moderate protein intake', 'Limit NSAID use'], low: ['Adequate protein intake'] },
    whenToSeeDoctor: { high: 'Persistent elevation or rising trend.', low: 'Usually not needed.' },
    preAnalyticalConfounders: ['Muscle mass', 'Cooked meat consumption', 'Creatine supplements'],
    medicationsAffecting: ['NSAIDs', 'ACE inhibitors', 'Trimethoprim'],
    relatedBiomarkers: ['EGFR', 'BUN', 'POTASSIUM'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'EGFR',
    name: 'Estimated GFR',
    aliases: ['eGFR', 'Glomerular Filtration Rate', 'GFR'],
    category: 'kidney',
    specimenType: 'calculated',
    defaultUnit: 'mL/min/1.73m²',
    referenceRanges: [
      { sex: 'any', min: 90, max: null, unit: 'mL/min/1.73m²', source: 'KDIGO' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 15, unit: 'mL/min/1.73m²', severity: 'critical', message: 'Severely reduced kidney function (Stage 5 CKD).', action: 'Seek immediate nephrology consultation.' },
      { direction: 'low', value: 30, unit: 'mL/min/1.73m²', severity: 'warning', message: 'Significantly reduced kidney function.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'How well the kidneys filter waste from the blood.',
    whatResultMayMean: { high: 'Usually not concerning; can indicate hyperfiltration.', low: 'May indicate chronic kidney disease at various stages.' },
    commonNonDangerousReasons: { high: ['Pregnancy', 'High-protein meal'], low: ['Age-related decline', 'Dehydration'] },
    whenItMatters: 'Primary marker for staging chronic kidney disease.',
    dailyLifeActions: { high: [], low: ['Stay hydrated', 'Control blood pressure', 'Control blood sugar', 'Limit NSAIDs'] },
    whenToSeeDoctor: { high: 'Usually not needed.', low: 'eGFR below 60 on two occasions 3 months apart.' },
    preAnalyticalConfounders: ['Calculated from creatinine — same confounders apply', 'Formula depends on age, sex'],
    medicationsAffecting: ['Same as creatinine'],
    relatedBiomarkers: ['CREATININE', 'BUN'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'BUN',
    name: 'Blood Urea Nitrogen',
    aliases: ['BUN', 'Urea', 'Urea Nitrogen'],
    category: 'kidney',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 7, max: 20, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 100, unit: 'mg/dL', severity: 'critical', message: 'Severely elevated BUN — possible kidney failure or upper GI bleeding.', action: 'Seek immediate medical attention.' },
      { direction: 'high', value: 40, unit: 'mg/dL', severity: 'warning', message: 'Significantly elevated BUN.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'A waste product from protein metabolism, filtered by the kidneys.',
    whatResultMayMean: { high: 'May indicate dehydration, high-protein diet, kidney dysfunction, or GI bleeding.', low: 'May indicate low-protein diet, liver disease, or overhydration.' },
    commonNonDangerousReasons: { high: ['Dehydration', 'High-protein diet'], low: ['Low-protein diet', 'Overhydration'] },
    whenItMatters: 'When evaluating kidney function and hydration status.',
    dailyLifeActions: { high: ['Stay hydrated', 'Moderate protein intake'], low: ['Adequate protein intake'] },
    whenToSeeDoctor: { high: 'Persistent elevation with low eGFR.', low: 'Usually not needed unless with liver symptoms.' },
    preAnalyticalConfounders: ['Diet', 'Hydration status', 'GI bleeding'],
    medicationsAffecting: ['Corticosteroids', 'Tetracyclines'],
    relatedBiomarkers: ['CREATININE', 'EGFR'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'TSH',
    name: 'Thyroid Stimulating Hormone',
    aliases: ['TSH', 'Thyrotropin'],
    category: 'thyroid',
    specimenType: 'serum',
    defaultUnit: 'mIU/L',
    alternativeUnits: ['µIU/mL'],
    referenceRanges: [
      { sex: 'any', min: 0.4, max: 4.0, unit: 'mIU/L', source: 'ATA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 50, unit: 'mIU/L', severity: 'critical', message: 'Severely elevated TSH — severe hypothyroidism.', action: 'Contact your healthcare provider urgently.' },
      { direction: 'low', value: 0.1, unit: 'mIU/L', severity: 'warning', message: 'Very low TSH — possible hyperthyroidism.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'A pituitary hormone that controls thyroid function.',
    whatResultMayMean: { high: 'May indicate hypothyroidism (underactive thyroid).', low: 'May indicate hyperthyroidism (overactive thyroid).' },
    commonNonDangerousReasons: { high: ['Subclinical hypothyroidism', 'Recovery from illness'], low: ['Subclinical hyperthyroidism', 'Excessive thyroid medication'] },
    whenItMatters: 'First-line screening test for thyroid disorders.',
    dailyLifeActions: { high: ['Adequate iodine and selenium', 'Manage stress'], low: ['Reduce caffeine', 'Bone-protective nutrition'] },
    whenToSeeDoctor: { high: 'TSH above 10 or symptoms of hypothyroidism.', low: 'TSH below 0.1 or symptoms of hyperthyroidism.' },
    preAnalyticalConfounders: ['Time of day (highest in morning)', 'Biotin supplements interfere with assay', 'Recent illness'],
    medicationsAffecting: ['Levothyroxine', 'Amiodarone', 'Lithium', 'Biotin'],
    relatedBiomarkers: ['FT4', 'FT3'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'FT4',
    name: 'Free Thyroxine',
    aliases: ['Free T4', 'FT4', 'Thyroxine Free'],
    category: 'thyroid',
    specimenType: 'serum',
    defaultUnit: 'ng/dL',
    referenceRanges: [
      { sex: 'any', min: 0.8, max: 1.8, unit: 'ng/dL', source: 'ATA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 5.0, unit: 'ng/dL', severity: 'critical', message: 'Severely elevated FT4 — thyroid storm risk.', action: 'Seek immediate medical attention.' },
      { direction: 'low', value: 0.4, unit: 'ng/dL', severity: 'warning', message: 'Very low FT4 — significant hypothyroidism.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'The active, unbound form of the thyroid hormone T4.',
    whatResultMayMean: { high: 'May indicate hyperthyroidism or excessive thyroid medication.', low: 'May indicate hypothyroidism.' },
    commonNonDangerousReasons: { high: ['Thyroid medication adjustment'], low: ['Subclinical hypothyroidism'] },
    whenItMatters: 'When TSH is abnormal and thyroid disease needs characterization.',
    dailyLifeActions: { high: ['Reduce caffeine', 'Monitor heart rate'], low: ['Adequate iodine'] },
    whenToSeeDoctor: { high: 'Elevated with symptoms of hyperthyroidism.', low: 'Low with elevated TSH.' },
    preAnalyticalConfounders: ['Biotin supplements', 'Pregnancy', 'Acute illness'],
    medicationsAffecting: ['Levothyroxine', 'Amiodarone', 'Heparin'],
    relatedBiomarkers: ['TSH', 'FT3'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'FT3',
    name: 'Free Triiodothyronine',
    aliases: ['Free T3', 'FT3', 'Triiodothyronine Free'],
    category: 'thyroid',
    specimenType: 'serum',
    defaultUnit: 'pg/mL',
    referenceRanges: [
      { sex: 'any', min: 2.0, max: 4.4, unit: 'pg/mL', source: 'ATA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 8.0, unit: 'pg/mL', severity: 'critical', message: 'Very high FT3 — risk of thyrotoxicosis.', action: 'Seek immediate medical attention.' },
    ],
    whatItMeasures: 'The active, unbound form of the thyroid hormone T3.',
    whatResultMayMean: { high: 'May indicate hyperthyroidism, especially T3 thyrotoxicosis.', low: 'May indicate hypothyroidism or non-thyroidal illness.' },
    commonNonDangerousReasons: { high: ['Thyroid medication'], low: ['Acute illness (sick euthyroid)'] },
    whenItMatters: 'When hyperthyroidism is suspected but FT4 is normal.',
    dailyLifeActions: { high: ['Reduce stimulants'], low: ['Rest and recovery if ill'] },
    whenToSeeDoctor: { high: 'Elevated with low TSH.', low: 'Low with elevated TSH and low FT4.' },
    preAnalyticalConfounders: ['Biotin', 'Acute illness'],
    medicationsAffecting: ['Levothyroxine', 'Amiodarone'],
    relatedBiomarkers: ['TSH', 'FT4'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'FERRITIN',
    name: 'Ferritin',
    aliases: ['Ferritin', 'Serum Ferritin'],
    category: 'iron',
    specimenType: 'serum',
    defaultUnit: 'ng/mL',
    alternativeUnits: ['µg/L'],
    referenceRanges: [
      { sex: 'male', min: 30, max: 400, unit: 'ng/mL', source: 'WHO' },
      { sex: 'female', min: 15, max: 150, unit: 'ng/mL', source: 'WHO' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 1000, unit: 'ng/mL', severity: 'critical', message: 'Very high ferritin — possible iron overload or serious underlying condition.', action: 'Seek medical evaluation promptly.' },
      { direction: 'low', value: 10, unit: 'ng/mL', severity: 'warning', message: 'Very low ferritin — iron stores depleted.', action: 'Contact your healthcare provider for iron supplementation.' },
    ],
    whatItMeasures: 'The body\'s iron storage protein. Reflects total iron stores.',
    whatResultMayMean: { high: 'May indicate iron overload, inflammation, liver disease, or malignancy.', low: 'Strongly suggests iron deficiency, even before anemia develops.' },
    commonNonDangerousReasons: { high: ['Acute inflammation', 'Alcohol use', 'Metabolic syndrome'], low: ['Menstruation', 'Vegetarian diet', 'Endurance exercise'] },
    whenItMatters: 'Most sensitive marker for iron deficiency. Also rises with inflammation.',
    dailyLifeActions: { high: ['Avoid iron supplements', 'Limit red meat', 'Avoid alcohol'], low: ['Iron-rich foods', 'Vitamin C with meals', 'Avoid tea/coffee with meals'] },
    whenToSeeDoctor: { high: 'Values above 500 or with other elevated liver markers.', low: 'Values below 20, especially with fatigue.' },
    preAnalyticalConfounders: ['Acute phase reactant — rises with inflammation', 'Fasting not required'],
    medicationsAffecting: ['Iron supplements', 'Oral contraceptives'],
    relatedBiomarkers: ['HGB', 'MCV', 'CRP'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'B12',
    name: 'Vitamin B12',
    aliases: ['B12', 'Cobalamin', 'Cyanocobalamin'],
    category: 'vitamin',
    specimenType: 'serum',
    defaultUnit: 'pg/mL',
    alternativeUnits: ['pmol/L'],
    referenceRanges: [
      { sex: 'any', min: 200, max: 900, unit: 'pg/mL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 150, unit: 'pg/mL', severity: 'warning', message: 'Low B12 — risk of neurological damage if untreated.', action: 'Contact your healthcare provider for supplementation.' },
    ],
    whatItMeasures: 'Vitamin B12 level, essential for nerve function and red blood cell production.',
    whatResultMayMean: { high: 'May indicate liver disease, blood disorders, or supplementation.', low: 'May indicate deficiency from diet, malabsorption, or pernicious anemia.' },
    commonNonDangerousReasons: { high: ['B12 supplementation'], low: ['Vegan/vegetarian diet', 'Aging (reduced absorption)'] },
    whenItMatters: 'Deficiency can cause irreversible nerve damage if untreated.',
    dailyLifeActions: { high: [], low: ['B12-rich foods (meat, fish, dairy)', 'Consider sublingual B12 supplement'] },
    whenToSeeDoctor: { high: 'If not supplementing and unexplained.', low: 'Values below 300 with symptoms (tingling, fatigue, memory issues).' },
    preAnalyticalConfounders: ['Recent supplementation', 'Biotin interferes with some assays'],
    medicationsAffecting: ['Metformin (lowers B12)', 'Proton pump inhibitors', 'B12 supplements'],
    relatedBiomarkers: ['FOLATE', 'MCV', 'HGB'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'FOLATE',
    name: 'Folate',
    aliases: ['Folic Acid', 'Vitamin B9', 'Serum Folate'],
    category: 'vitamin',
    specimenType: 'serum',
    defaultUnit: 'ng/mL',
    alternativeUnits: ['nmol/L'],
    referenceRanges: [
      { sex: 'any', min: 3.0, max: 20.0, unit: 'ng/mL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 2.0, unit: 'ng/mL', severity: 'warning', message: 'Low folate — risk of megaloblastic anemia.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'Vitamin B9 (folate), essential for DNA synthesis and red blood cell formation.',
    whatResultMayMean: { high: 'Usually from supplementation; rarely a concern.', low: 'May indicate dietary deficiency, malabsorption, or increased demand.' },
    commonNonDangerousReasons: { high: ['Supplementation'], low: ['Poor diet', 'Pregnancy', 'Alcohol use'] },
    whenItMatters: 'Critical during pregnancy. Deficiency causes macrocytic anemia.',
    dailyLifeActions: { high: [], low: ['Leafy greens, legumes, fortified cereals', 'Consider folic acid supplement'] },
    whenToSeeDoctor: { high: 'Usually not needed.', low: 'Values below 3 or if planning pregnancy.' },
    preAnalyticalConfounders: ['Recent meal affects serum folate', 'RBC folate is more stable'],
    medicationsAffecting: ['Methotrexate', 'Phenytoin', 'Folic acid supplements'],
    relatedBiomarkers: ['B12', 'MCV', 'HGB'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'CRP',
    name: 'C-Reactive Protein',
    aliases: ['CRP', 'hs-CRP', 'High-Sensitivity CRP'],
    category: 'inflammation',
    specimenType: 'serum',
    defaultUnit: 'mg/L',
    referenceRanges: [
      { sex: 'any', min: null, max: 3.0, unit: 'mg/L', source: 'AHA' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 100, unit: 'mg/L', severity: 'critical', message: 'Severely elevated CRP — significant infection or inflammation.', action: 'Seek medical attention.' },
      { direction: 'high', value: 10, unit: 'mg/L', severity: 'warning', message: 'Elevated CRP — active inflammation.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'A protein produced by the liver in response to inflammation anywhere in the body.',
    whatResultMayMean: { high: 'May indicate infection, autoimmune disease, tissue injury, or cardiovascular risk.', low: 'Suggests no significant systemic inflammation.' },
    commonNonDangerousReasons: { high: ['Recent cold/flu', 'Intense exercise', 'Obesity'], low: [] },
    whenItMatters: 'Non-specific but very sensitive marker of inflammation.',
    dailyLifeActions: { high: ['Anti-inflammatory diet', 'Regular exercise', 'Adequate sleep', 'Maintain healthy weight'], low: [] },
    whenToSeeDoctor: { high: 'Persistent elevation above 3 mg/L or acute elevation.', low: 'Not needed.' },
    preAnalyticalConfounders: ['Acute illness', 'Obesity', 'Oral contraceptives', 'Hormone replacement'],
    medicationsAffecting: ['Statins (lower CRP)', 'NSAIDs', 'Corticosteroids'],
    relatedBiomarkers: ['ESR', 'WBC', 'FERRITIN'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'ESR',
    name: 'Erythrocyte Sedimentation Rate',
    aliases: ['ESR', 'Sed Rate'],
    category: 'inflammation',
    specimenType: 'whole blood',
    defaultUnit: 'mm/hr',
    referenceRanges: [
      { sex: 'male', min: 0, max: 15, unit: 'mm/hr', source: 'CLSI', ageMax: 50 },
      { sex: 'male', min: 0, max: 20, unit: 'mm/hr', source: 'CLSI', ageMin: 50 },
      { sex: 'female', min: 0, max: 20, unit: 'mm/hr', source: 'CLSI', ageMax: 50 },
      { sex: 'female', min: 0, max: 30, unit: 'mm/hr', source: 'CLSI', ageMin: 50 },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 100, unit: 'mm/hr', severity: 'warning', message: 'Very high ESR — significant inflammation or possible malignancy.', action: 'Contact your healthcare provider.' },
    ],
    whatItMeasures: 'How quickly red blood cells settle to the bottom of a tube, indicating inflammation.',
    whatResultMayMean: { high: 'May indicate infection, autoimmune disease, or malignancy.', low: 'Suggests no significant inflammation.' },
    commonNonDangerousReasons: { high: ['Age (naturally increases)', 'Pregnancy', 'Anemia'], low: [] },
    whenItMatters: 'Non-specific inflammation marker; more useful for monitoring than diagnosis.',
    dailyLifeActions: { high: ['Anti-inflammatory lifestyle'], low: [] },
    whenToSeeDoctor: { high: 'Persistent elevation above 40 mm/hr.', low: 'Not needed.' },
    preAnalyticalConfounders: ['Age', 'Sex', 'Pregnancy', 'Anemia affects results'],
    medicationsAffecting: ['NSAIDs', 'Corticosteroids'],
    relatedBiomarkers: ['CRP', 'WBC'],
    evidenceTier: 2,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'SODIUM',
    name: 'Sodium',
    aliases: ['Na', 'Na+', 'Serum Sodium'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mmol/L',
    referenceRanges: [
      { sex: 'any', min: 136, max: 145, unit: 'mmol/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 155, unit: 'mmol/L', severity: 'critical', message: 'Severe hypernatremia — risk of neurological damage.', action: 'Seek immediate medical attention.' },
      { direction: 'low', value: 120, unit: 'mmol/L', severity: 'critical', message: 'Severe hyponatremia — risk of seizures and brain edema.', action: 'Seek immediate medical attention.' },
    ],
    whatItMeasures: 'The concentration of sodium in the blood, critical for fluid balance and nerve function.',
    whatResultMayMean: { high: 'May indicate dehydration, diabetes insipidus, or excess sodium intake.', low: 'May indicate overhydration, SIADH, heart failure, or certain medications.' },
    commonNonDangerousReasons: { high: ['Mild dehydration'], low: ['Excessive water intake', 'Diuretics'] },
    whenItMatters: 'Critical electrolyte — abnormalities can cause serious neurological symptoms.',
    dailyLifeActions: { high: ['Increase water intake', 'Reduce salt'], low: ['Moderate fluid intake', 'Avoid excessive water'] },
    whenToSeeDoctor: { high: 'Values above 148 or with symptoms.', low: 'Values below 130 or with confusion/nausea.' },
    preAnalyticalConfounders: ['Lipemia (pseudohyponatremia)', 'IV fluids'],
    medicationsAffecting: ['Diuretics', 'SSRI antidepressants', 'Lithium'],
    relatedBiomarkers: ['POTASSIUM', 'BUN', 'CREATININE'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'POTASSIUM',
    name: 'Potassium',
    aliases: ['K', 'K+', 'Serum Potassium'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mmol/L',
    referenceRanges: [
      { sex: 'any', min: 3.5, max: 5.0, unit: 'mmol/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 6.0, unit: 'mmol/L', severity: 'critical', message: 'Dangerously high potassium — risk of cardiac arrhythmia.', action: 'Seek immediate medical attention.' },
      { direction: 'low', value: 3.0, unit: 'mmol/L', severity: 'critical', message: 'Dangerously low potassium — risk of cardiac arrhythmia.', action: 'Seek immediate medical attention.' },
    ],
    whatItMeasures: 'The concentration of potassium in the blood, critical for heart and muscle function.',
    whatResultMayMean: { high: 'May indicate kidney disease, acidosis, tissue damage, or hemolyzed sample.', low: 'May indicate loss from vomiting, diarrhea, diuretics, or poor intake.' },
    commonNonDangerousReasons: { high: ['Hemolyzed sample (most common lab artifact)', 'Fist clenching during draw'], low: ['Diuretics', 'Excessive sweating'] },
    whenItMatters: 'Critical for heart rhythm — both high and low can be dangerous.',
    dailyLifeActions: { high: ['Avoid high-potassium foods if kidney impaired'], low: ['Potassium-rich foods: bananas, potatoes, spinach'] },
    whenToSeeDoctor: { high: 'Values above 5.5 — confirm with repeat sample.', low: 'Values below 3.5 or with muscle cramps/weakness.' },
    preAnalyticalConfounders: ['Hemolysis (very common false elevation)', 'Fist clenching', 'Tourniquet time'],
    medicationsAffecting: ['ACE inhibitors', 'Spironolactone', 'Diuretics', 'NSAIDs'],
    relatedBiomarkers: ['SODIUM', 'CREATININE', 'EGFR'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'ALBUMIN',
    name: 'Albumin',
    aliases: ['Alb', 'Serum Albumin'],
    category: 'protein',
    specimenType: 'serum',
    defaultUnit: 'g/dL',
    referenceRanges: [
      { sex: 'any', min: 3.5, max: 5.5, unit: 'g/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 2.0, unit: 'g/dL', severity: 'critical', message: 'Severely low albumin — risk of edema and poor healing.', action: 'Seek medical attention.' },
    ],
    whatItMeasures: 'The most abundant protein in blood, important for maintaining fluid balance and transporting substances.',
    whatResultMayMean: { high: 'May indicate dehydration.', low: 'May indicate liver disease, kidney disease, malnutrition, or inflammation.' },
    commonNonDangerousReasons: { high: ['Dehydration'], low: ['Acute illness', 'Inflammation'] },
    whenItMatters: 'Low albumin is a marker of chronic illness severity.',
    dailyLifeActions: { high: ['Stay hydrated'], low: ['Adequate protein intake', 'Address underlying causes'] },
    whenToSeeDoctor: { high: 'Usually not needed.', low: 'Values below 3.0 or with edema.' },
    preAnalyticalConfounders: ['Dehydration concentrates it', 'Posture affects levels'],
    medicationsAffecting: ['IV fluids dilute it', 'Corticosteroids'],
    relatedBiomarkers: ['BILIRUBIN', 'ALT', 'CREATININE'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),

  kb({
    code: 'CALCIUM',
    name: 'Calcium',
    aliases: ['Ca', 'Ca2+', 'Serum Calcium', 'Total Calcium'],
    category: 'mineral',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 8.5, max: 10.5, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 13.0, unit: 'mg/dL', severity: 'critical', message: 'Severe hypercalcemia — risk of cardiac and neurological complications.', action: 'Seek immediate medical attention.' },
      { direction: 'low', value: 7.0, unit: 'mg/dL', severity: 'critical', message: 'Severe hypocalcemia — risk of tetany and cardiac arrhythmia.', action: 'Seek immediate medical attention.' },
    ],
    whatItMeasures: 'The amount of calcium in the blood, essential for bone health, heart, and nerve function.',
    whatResultMayMean: { high: 'May indicate hyperparathyroidism, malignancy, or excess vitamin D.', low: 'May indicate vitamin D deficiency, hypoparathyroidism, or kidney disease.' },
    commonNonDangerousReasons: { high: ['Mild dehydration'], low: ['Low albumin (pseudohypocalcemia)', 'Vitamin D deficiency'] },
    whenItMatters: 'Abnormal calcium affects heart, nerves, and bones.',
    dailyLifeActions: { high: ['Stay hydrated', 'Limit calcium supplements'], low: ['Adequate calcium and vitamin D intake'] },
    whenToSeeDoctor: { high: 'Values above 10.5 confirmed on repeat.', low: 'Values below 8.0 or with symptoms.' },
    preAnalyticalConfounders: ['Albumin level affects total calcium', 'Tourniquet time'],
    medicationsAffecting: ['Thiazide diuretics', 'Lithium', 'Vitamin D supplements'],
    relatedBiomarkers: ['ALBUMIN', 'CREATININE'],
    evidenceTier: 1,
    lastReviewed: '2025-01-15',
  }),
];

// Build lookup map
export const BIOMARKER_KNOWLEDGE = new Map<string, BiomarkerKnowledge>(
  BIOMARKER_LIST.map((b) => [b.code, b])
);

// Export list for iteration
export const ALL_BIOMARKERS = BIOMARKER_LIST;

// Lookup by alias
export function findBiomarkerByAlias(alias: string): BiomarkerKnowledge | undefined {
  const normalized = alias.trim().toLowerCase();
  return BIOMARKER_LIST.find(
    (b) =>
      b.code.toLowerCase() === normalized ||
      b.name.toLowerCase() === normalized ||
      b.aliases.some((a) => a.toLowerCase() === normalized)
  );
}
