import type { BiomarkerKnowledge } from './types';

export const cbcBiomarkers: BiomarkerKnowledge[] = [
  {
    code: 'WBC',
    name: 'White Blood Cell Count',
    aliases: ['leukocytes', 'white blood cells', 'leucocytes', 'WCC'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10⁹/L',
    alternativeUnits: ['×10³/µL', 'cells/µL'],
    referenceRanges: [
      { sex: 'any', min: 4.5, max: 11.0, unit: '×10⁹/L', source: 'WHO/CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 30.0, unit: '×10⁹/L', severity: 'critical', message: 'Severely elevated WBC count — may indicate serious infection, leukemia, or other hematologic emergency.', action: 'Seek urgent medical evaluation immediately.' },
      { direction: 'low', value: 2.0, unit: '×10⁹/L', severity: 'critical', message: 'Severely low WBC count — significantly increased risk of infection.', action: 'Contact your clinician urgently; avoid crowds and sick contacts.' },
      { direction: 'high', value: 15.0, unit: '×10⁹/L', severity: 'warning', message: 'Elevated WBC may indicate active infection or inflammatory process.', action: 'Discuss with your clinician to identify the cause.' },
      { direction: 'low', value: 3.5, unit: '×10⁹/L', severity: 'warning', message: 'Low WBC count may reduce your ability to fight infections.', action: 'Follow up with your clinician for further evaluation.' },
    ],
    whatItMeasures: 'The total number of white blood cells in your blood. White blood cells are a key part of your immune system and help fight infections, viruses, and other foreign invaders.',
    whatResultMayMean: {
      high: 'An elevated WBC count (leukocytosis) may indicate an active infection, inflammation, stress response, allergic reaction, or in rarer cases, a blood disorder such as leukemia. The specific type of white cell elevated helps narrow the cause.',
      low: 'A low WBC count (leukopenia) may indicate bone marrow suppression, viral infections, autoimmune conditions, nutritional deficiencies, or medication side effects. It can increase susceptibility to infections.',
    },
    commonNonDangerousReasons: {
      high: [
        'Recent physical or emotional stress',
        'Strenuous exercise within hours before the blood draw',
        'Active minor infection such as a cold or urinary tract infection',
        'Smoking',
        'Corticosteroid use',
        'Pregnancy (mild elevation is normal)',
      ],
      low: [
        'Recent viral infection',
        'Normal variation in some ethnic groups (benign ethnic neutropenia)',
        'Certain medications such as antibiotics or anti-seizure drugs',
      ],
    },
    whenItMatters: 'WBC count is important when evaluating suspected infections, monitoring immune system health, assessing response to chemotherapy, or investigating unexplained fevers, fatigue, or frequent infections.',
    dailyLifeActions: {
      high: [
        'Ensure adequate rest to support immune function',
        'Stay well-hydrated',
        'If you smoke, consider a cessation program — smoking chronically elevates WBC',
        'Manage chronic stress through relaxation techniques, which may help support a healthy immune balance',
      ],
      low: [
        'Practice good hand hygiene to reduce infection risk',
        'Avoid close contact with people who are sick',
        'Ensure adequate nutrition, including B12, folate, and zinc',
        'Get prompt medical attention for any fever or signs of infection',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if WBC remains elevated on repeat testing, if you have unexplained fevers, night sweats, or unintended weight loss, or if the count exceeds 15 ×10⁹/L.',
      low: 'See a clinician if WBC is below 3.5 ×10⁹/L, if you experience recurrent infections, mouth sores, or persistent fatigue.',
    },
    preAnalyticalConfounders: [
      'Vigorous exercise within 24 hours before the test',
      'Acute emotional or physical stress',
      'Time of day (WBC tends to be lower in the morning)',
      'Smoking status',
      'Recent meals',
      'Dehydration (may falsely concentrate the count)',
    ],
    medicationsAffecting: [
      'Corticosteroids (increase)',
      'Lithium (increase)',
      'Beta-agonists such as albuterol (increase)',
      'Chemotherapy agents (decrease)',
      'Methotrexate (decrease)',
      'Carbamazepine (decrease)',
      'Clozapine (decrease)',
      'Antibiotics such as trimethoprim-sulfamethoxazole (decrease)',
    ],
    relatedBiomarkers: ['NEUT', 'LYMPH', 'MONO', 'EOS', 'BASO', 'RBC', 'PLT'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'RBC',
    name: 'Red Blood Cell Count',
    aliases: ['erythrocytes', 'red blood cells', 'red cell count'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10¹²/L',
    alternativeUnits: ['×10⁶/µL', 'M/µL'],
    referenceRanges: [
      { sex: 'male', min: 4.5, max: 5.9, unit: '×10¹²/L', source: 'WHO/CLSI' },
      { sex: 'female', min: 4.0, max: 5.2, unit: '×10¹²/L', source: 'WHO/CLSI', pregnancyCaveat: 'Lower values are expected during pregnancy due to plasma volume expansion.' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 6.5, unit: '×10¹²/L', severity: 'warning', message: 'Elevated RBC count — may indicate polycythemia or chronic hypoxia.', action: 'Discuss with your clinician for further evaluation.' },
      { direction: 'low', value: 3.0, unit: '×10¹²/L', severity: 'critical', message: 'Severely low RBC count — significant anemia that may require urgent treatment.', action: 'Seek medical evaluation promptly.' },
      { direction: 'low', value: 3.8, unit: '×10¹²/L', severity: 'warning', message: 'Low RBC count may indicate anemia.', action: 'Follow up with your clinician.' },
    ],
    whatItMeasures: 'The number of red blood cells per volume of blood. Red blood cells carry oxygen from your lungs to tissues throughout the body and return carbon dioxide to the lungs for exhalation.',
    whatResultMayMean: {
      high: 'An elevated RBC count (polycythemia) may result from chronic low oxygen (such as living at high altitude, smoking, or lung disease), dehydration, or rarely, polycythemia vera — a bone marrow disorder.',
      low: 'A low RBC count indicates anemia, which may be caused by iron deficiency, chronic disease, blood loss, vitamin deficiency (B12 or folate), or bone marrow problems.',
    },
    commonNonDangerousReasons: {
      high: [
        'Living at high altitude',
        'Dehydration (relative increase)',
        'Smoking',
        'Endurance athletic training',
      ],
      low: [
        'Heavy menstrual periods',
        'Pregnancy (hemodilution)',
        'Recent blood donation',
        'Mild iron or vitamin deficiency from diet',
      ],
    },
    whenItMatters: 'RBC count helps assess oxygen-carrying capacity and is important when investigating fatigue, shortness of breath, dizziness, or pale skin.',
    dailyLifeActions: {
      high: [
        'Stay well-hydrated, as dehydration can concentrate red cells',
        'If you smoke, consider cessation — smoking increases RBC production',
        'Avoid iron supplements unless directed by your clinician',
      ],
      low: [
        'Consume iron-rich foods such as lean meats, beans, and dark leafy greens',
        'Pair iron-rich foods with vitamin C to enhance absorption',
        'Avoid tea or coffee with meals, as they can reduce iron absorption',
        'Ensure adequate B12 and folate intake',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if RBC remains elevated on repeat testing, especially with headaches, dizziness, visual changes, or itching after showers.',
      low: 'See a clinician if you feel persistently fatigued, short of breath at rest or with minimal exertion, or if RBC is below 3.8 ×10¹²/L.',
    },
    preAnalyticalConfounders: [
      'Dehydration (falsely elevated)',
      'Overhydration (falsely low)',
      'Tourniquet time during blood draw',
      'Body position (standing vs. supine)',
      'Altitude of residence',
    ],
    medicationsAffecting: [
      'Erythropoietin (EPO) injections (increase)',
      'Androgens/testosterone (increase)',
      'Chemotherapy agents (decrease)',
      'ACE inhibitors (may slightly decrease)',
      'Zidovudine (decrease)',
    ],
    relatedBiomarkers: ['HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'RDW', 'FERRITIN', 'FE'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'HGB',
    name: 'Hemoglobin',
    aliases: ['Hgb', 'Hb', 'haemoglobin'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: 'g/dL',
    alternativeUnits: ['g/L', 'mmol/L'],
    referenceRanges: [
      { sex: 'male', min: 13.5, max: 17.5, unit: 'g/dL', source: 'WHO/CLSI' },
      { sex: 'female', min: 12.0, max: 16.0, unit: 'g/dL', source: 'WHO/CLSI', pregnancyCaveat: 'Hemoglobin normally decreases during pregnancy; values above 11.0 g/dL are generally considered adequate in the second trimester.' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 7.0, unit: 'g/dL', severity: 'critical', message: 'Critically low hemoglobin — transfusion may be needed. Risk of organ damage from inadequate oxygen delivery.', action: 'Seek emergency medical care immediately.' },
      { direction: 'low', value: 10.0, unit: 'g/dL', severity: 'warning', message: 'Moderate anemia — may cause significant symptoms such as fatigue and shortness of breath.', action: 'See your clinician promptly for evaluation and treatment.' },
      { direction: 'high', value: 20.0, unit: 'g/dL', severity: 'critical', message: 'Dangerously elevated hemoglobin — increased risk of blood clots, stroke, or heart attack.', action: 'Seek urgent medical evaluation.' },
    ],
    whatItMeasures: 'The concentration of hemoglobin in your blood. Hemoglobin is the iron-containing protein in red blood cells responsible for carrying oxygen from the lungs to the rest of the body.',
    whatResultMayMean: {
      high: 'Elevated hemoglobin may indicate dehydration, chronic lung disease, polycythemia vera, smoking, or living at high altitude. Very high levels increase the risk of blood clots.',
      low: 'Low hemoglobin (anemia) can cause fatigue, weakness, and shortness of breath. Common causes include iron deficiency, chronic disease, blood loss, and vitamin deficiencies.',
    },
    commonNonDangerousReasons: {
      high: [
        'Dehydration',
        'Living at high altitude',
        'Smoking',
        'Intense endurance exercise',
      ],
      low: [
        'Heavy menstrual periods',
        'Pregnancy',
        'Recent blood donation',
        'Vegetarian or vegan diet with inadequate iron intake',
        'Mild chronic inflammation',
      ],
    },
    whenItMatters: 'Hemoglobin is the primary marker for diagnosing and monitoring anemia and polycythemia. It is essential when evaluating fatigue, pallor, dizziness, or shortness of breath.',
    dailyLifeActions: {
      high: [
        'Stay well-hydrated throughout the day',
        'Avoid smoking and secondhand smoke',
        'Discuss any supplements (including iron) with your clinician',
      ],
      low: [
        'Include iron-rich foods in your diet such as red meat, lentils, spinach, and fortified cereals',
        'Eat vitamin C-rich foods alongside iron sources to improve absorption',
        'Avoid calcium supplements and antacids at the same time as iron-rich meals',
        'If vegetarian or vegan, pay special attention to iron and B12 intake',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if hemoglobin is above 18 g/dL in men or 17 g/dL in women, particularly with headaches, blurred vision, or skin redness.',
      low: 'See a clinician if hemoglobin is below 11 g/dL, or sooner if you have chest pain, severe fatigue, rapid heartbeat, or dizziness at rest.',
    },
    preAnalyticalConfounders: [
      'Dehydration (falsely elevated)',
      'Overhydration or IV fluids (falsely low)',
      'Tourniquet application time',
      'Body position during blood draw',
      'Smoking status',
      'Altitude of residence',
    ],
    medicationsAffecting: [
      'Iron supplements (increase when correcting deficiency)',
      'Erythropoietin (increase)',
      'Androgens (increase)',
      'Chemotherapy agents (decrease)',
      'NSAIDs — may cause occult GI bleeding leading to decrease',
      'Antiretrovirals such as zidovudine (decrease)',
    ],
    relatedBiomarkers: ['RBC', 'HCT', 'MCV', 'MCH', 'MCHC', 'FERRITIN', 'FE', 'TIBC'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'HCT',
    name: 'Hematocrit',
    aliases: ['Hct', 'packed cell volume', 'PCV', 'crit'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '%',
    alternativeUnits: ['L/L'],
    referenceRanges: [
      { sex: 'male', min: 40, max: 54, unit: '%', source: 'WHO/CLSI' },
      { sex: 'female', min: 36, max: 48, unit: '%', source: 'WHO/CLSI', pregnancyCaveat: 'Hematocrit decreases during pregnancy due to plasma volume expansion; values above 33% are generally adequate.' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 20, unit: '%', severity: 'critical', message: 'Critically low hematocrit — severely impaired oxygen delivery.', action: 'Seek emergency medical care.' },
      { direction: 'low', value: 30, unit: '%', severity: 'warning', message: 'Low hematocrit suggests significant anemia.', action: 'See your clinician for further evaluation.' },
      { direction: 'high', value: 60, unit: '%', severity: 'critical', message: 'Dangerously elevated hematocrit — very high risk of blood clots.', action: 'Seek urgent medical evaluation.' },
    ],
    whatItMeasures: 'The percentage of your blood volume that is made up of red blood cells. It reflects both the number and size of red blood cells relative to the liquid component of blood (plasma).',
    whatResultMayMean: {
      high: 'Elevated hematocrit may indicate dehydration, polycythemia, chronic lung disease, or living at high altitude. Very high values increase the risk of clotting and stroke.',
      low: 'Low hematocrit indicates anemia and may result from blood loss, nutritional deficiency, chronic disease, or bone marrow disorders.',
    },
    commonNonDangerousReasons: {
      high: ['Dehydration', 'High altitude', 'Smoking', 'Strenuous exercise'],
      low: ['Pregnancy', 'Overhydration', 'Recent blood donation', 'Heavy menstruation'],
    },
    whenItMatters: 'Hematocrit is a quick indicator of anemia or polycythemia and is used alongside hemoglobin to guide clinical decisions about transfusions and further workup.',
    dailyLifeActions: {
      high: [
        'Drink adequate water throughout the day',
        'Limit alcohol consumption, which can contribute to dehydration',
        'Avoid smoking',
      ],
      low: [
        'Focus on iron-rich and nutrient-dense foods',
        'Ensure adequate calorie and protein intake',
        'Address heavy menstrual bleeding with your clinician if applicable',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if hematocrit exceeds 54% in men or 48% in women, especially with symptoms such as headache, dizziness, or redness in the face.',
      low: 'See a clinician if hematocrit is below 33%, or if you experience fatigue, weakness, or shortness of breath.',
    },
    preAnalyticalConfounders: [
      'Dehydration (falsely elevated)',
      'IV fluid administration (falsely low)',
      'Tourniquet time',
      'Body position during draw',
    ],
    medicationsAffecting: [
      'Erythropoietin (increase)',
      'Androgens (increase)',
      'Chemotherapy (decrease)',
      'Fluids/IV hydration (decrease)',
    ],
    relatedBiomarkers: ['RBC', 'HGB', 'MCV'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'MCV',
    name: 'Mean Corpuscular Volume',
    aliases: ['mean cell volume'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: 'fL',
    referenceRanges: [
      { sex: 'any', min: 80, max: 100, unit: 'fL', source: 'WHO/CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 115, unit: 'fL', severity: 'warning', message: 'Significantly elevated MCV may indicate B12 or folate deficiency, or myelodysplastic syndrome.', action: 'See your clinician for B12, folate, and further workup.' },
      { direction: 'low', value: 70, unit: 'fL', severity: 'warning', message: 'Significantly low MCV suggests iron deficiency or thalassemia.', action: 'Discuss iron studies and hemoglobin electrophoresis with your clinician.' },
    ],
    whatItMeasures: 'The average size (volume) of a single red blood cell. It helps classify anemias as microcytic (small cells), normocytic (normal cells), or macrocytic (large cells).',
    whatResultMayMean: {
      high: 'Macrocytosis (large red cells) may indicate B12 or folate deficiency, excessive alcohol use, liver disease, hypothyroidism, or certain medications. It may also be seen in myelodysplastic syndromes.',
      low: 'Microcytosis (small red cells) most commonly indicates iron deficiency anemia or thalassemia trait. It can also occur with chronic disease or lead poisoning.',
    },
    commonNonDangerousReasons: {
      high: [
        'Moderate alcohol consumption',
        'B12 or folate insufficiency from diet',
        'Hypothyroidism',
        'Normal in newborns and pregnancy',
      ],
      low: [
        'Mild iron deficiency from diet or menstruation',
        'Thalassemia trait (a common inherited condition)',
      ],
    },
    whenItMatters: 'MCV is essential for classifying the type of anemia and guiding the diagnostic workup. It helps clinicians determine whether the cause is nutritional, genetic, or related to chronic disease.',
    dailyLifeActions: {
      high: [
        'Ensure adequate intake of B12-rich foods such as meat, fish, eggs, and dairy',
        'Consider B12 supplementation if following a vegan diet',
        'Limit alcohol consumption',
        'Include folate-rich foods such as leafy greens, legumes, and fortified grains',
      ],
      low: [
        'Eat iron-rich foods regularly',
        'Pair iron-rich foods with vitamin C sources',
        'Avoid drinking tea or coffee with iron-rich meals',
        'Discuss iron supplementation with your clinician if dietary changes are insufficient',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if MCV exceeds 105 fL to investigate B12, folate levels, thyroid function, and alcohol intake.',
      low: 'See a clinician if MCV is below 75 fL to evaluate for iron deficiency or thalassemia.',
    },
    preAnalyticalConfounders: [
      'Cold agglutinins (falsely elevated)',
      'Hyperglycemia (falsely elevated due to cell swelling in vitro)',
      'Very high WBC count (may interfere with measurement)',
    ],
    medicationsAffecting: [
      'Methotrexate (increase)',
      'Hydroxyurea (increase)',
      'Azathioprine (increase)',
      'Antiretrovirals such as zidovudine (increase)',
      'Phenytoin (increase)',
      'Metformin — long-term use may increase due to B12 depletion',
    ],
    relatedBiomarkers: ['RBC', 'HGB', 'MCH', 'MCHC', 'RDW', 'B12', 'FOLATE', 'FERRITIN'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'MCH',
    name: 'Mean Corpuscular Hemoglobin',
    aliases: ['mean cell hemoglobin'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: 'pg',
    referenceRanges: [
      { sex: 'any', min: 27, max: 33, unit: 'pg', source: 'WHO/CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 24, unit: 'pg', severity: 'warning', message: 'Low MCH suggests iron deficiency or thalassemia.', action: 'Evaluate iron status with your clinician.' },
      { direction: 'high', value: 36, unit: 'pg', severity: 'warning', message: 'Elevated MCH may indicate macrocytic anemia from B12 or folate deficiency.', action: 'Check B12 and folate levels.' },
    ],
    whatItMeasures: 'The average amount of hemoglobin inside a single red blood cell. It is closely correlated with MCV and helps classify anemias.',
    whatResultMayMean: {
      high: 'Elevated MCH often accompanies macrocytic anemias caused by B12 or folate deficiency, liver disease, or alcohol use.',
      low: 'Low MCH indicates hypochromic red cells, commonly seen in iron deficiency and thalassemia.',
    },
    commonNonDangerousReasons: {
      high: ['Mild B12 or folate insufficiency', 'Moderate alcohol intake'],
      low: ['Mild iron deficiency', 'Thalassemia trait'],
    },
    whenItMatters: 'MCH helps refine the classification of anemia when used alongside MCV and MCHC.',
    dailyLifeActions: {
      high: ['Ensure adequate B12 and folate intake', 'Moderate alcohol consumption'],
      low: ['Increase iron-rich foods in your diet', 'Take iron supplements only as directed by your clinician'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if MCH is above 35 pg, particularly with fatigue or neurological symptoms.',
      low: 'See a clinician if MCH is below 25 pg with associated fatigue or pallor.',
    },
    preAnalyticalConfounders: ['Same confounders as MCV — cold agglutinins, hyperglycemia, lipemia'],
    medicationsAffecting: ['Same as MCV — methotrexate, hydroxyurea, antiretrovirals may increase'],
    relatedBiomarkers: ['MCV', 'MCHC', 'HGB', 'RBC', 'FERRITIN'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'MCHC',
    name: 'Mean Corpuscular Hemoglobin Concentration',
    aliases: ['mean cell hemoglobin concentration'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: 'g/dL',
    alternativeUnits: ['g/L'],
    referenceRanges: [
      { sex: 'any', min: 32, max: 36, unit: 'g/dL', source: 'WHO/CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 30, unit: 'g/dL', severity: 'warning', message: 'Low MCHC indicates hypochromic red cells, commonly iron deficiency.', action: 'Discuss iron studies with your clinician.' },
      { direction: 'high', value: 37, unit: 'g/dL', severity: 'info', message: 'Elevated MCHC is unusual and may suggest spherocytosis or a lab artifact.', action: 'Discuss with your clinician if persistent.' },
    ],
    whatItMeasures: 'The average concentration of hemoglobin within red blood cells. Unlike MCH, which measures the total amount, MCHC measures the density of hemoglobin per unit volume of the cell.',
    whatResultMayMean: {
      high: 'Elevated MCHC is uncommon and may suggest hereditary spherocytosis, autoimmune hemolytic anemia, or a laboratory artifact (lipemia, cold agglutinins).',
      low: 'Low MCHC indicates that red cells are pale (hypochromic), typically from iron deficiency or thalassemia.',
    },
    commonNonDangerousReasons: {
      high: ['Lab artifact from lipemic sample', 'Cold agglutinins'],
      low: ['Mild iron deficiency', 'Thalassemia trait'],
    },
    whenItMatters: 'MCHC is most useful for identifying hypochromic anemias and for flagging possible hereditary spherocytosis when persistently elevated.',
    dailyLifeActions: {
      high: ['No specific lifestyle actions; elevated MCHC warrants clinical evaluation'],
      low: ['Increase dietary iron intake', 'Ensure adequate vitamin C to support iron absorption'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if MCHC is persistently above 36.5 g/dL, as it may indicate a red cell membrane disorder.',
      low: 'See a clinician if MCHC is below 31 g/dL, particularly with other signs of anemia.',
    },
    preAnalyticalConfounders: ['Lipemia (falsely elevated)', 'Cold agglutinins (falsely elevated)', 'Hyperglycemia'],
    medicationsAffecting: ['Generally not directly affected by medications; changes reflect underlying red cell indices'],
    relatedBiomarkers: ['MCV', 'MCH', 'HGB', 'RBC', 'FERRITIN', 'FE'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'RDW',
    name: 'Red Cell Distribution Width',
    aliases: ['RDW-CV', 'RDW-SD', 'red cell distribution width'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '%',
    referenceRanges: [
      { sex: 'any', min: 11.5, max: 14.5, unit: '%', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 18, unit: '%', severity: 'warning', message: 'Significantly elevated RDW indicates wide variation in red cell size, suggesting mixed or evolving anemia.', action: 'Evaluate with iron studies, B12, folate, and reticulocyte count.' },
    ],
    whatItMeasures: 'How much variation there is in the size of your red blood cells. A higher RDW means the red cells are more uneven in size (anisocytosis).',
    whatResultMayMean: {
      high: 'Elevated RDW may indicate iron deficiency (early stage), mixed nutritional deficiency (iron + B12), recent blood transfusion, or early response to treatment for anemia. It is also elevated in many chronic conditions.',
      low: 'A low RDW is generally not clinically significant. It means red cells are very uniform in size.',
    },
    commonNonDangerousReasons: {
      high: ['Early or mild iron deficiency', 'Recent recovery from illness', 'Mixed dietary insufficiency'],
      low: [],
    },
    whenItMatters: 'RDW helps distinguish iron deficiency anemia (elevated RDW) from thalassemia trait (normal RDW) when MCV is low. It also has emerging value as a general health marker.',
    dailyLifeActions: {
      high: [
        'Ensure a balanced diet with adequate iron, B12, and folate',
        'Have a comprehensive nutritional evaluation if RDW is persistently elevated',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if RDW is above 16% with abnormal hemoglobin or MCV, to determine the underlying cause.',
      low: 'Low RDW alone does not typically require follow-up.',
    },
    preAnalyticalConfounders: ['Cold agglutinins (falsely elevated)', 'Recent blood transfusion'],
    medicationsAffecting: ['Chemotherapy (increase due to mixed cell populations)', 'Iron supplementation may temporarily increase RDW as new cells are produced'],
    relatedBiomarkers: ['MCV', 'HGB', 'FERRITIN', 'B12', 'FOLATE'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'PLT',
    name: 'Platelet Count',
    aliases: ['platelets', 'thrombocytes', 'Plt'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10⁹/L',
    alternativeUnits: ['×10³/µL', 'K/µL'],
    referenceRanges: [
      { sex: 'any', min: 150, max: 400, unit: '×10⁹/L', source: 'WHO/CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 50, unit: '×10⁹/L', severity: 'critical', message: 'Severely low platelet count — risk of spontaneous bleeding.', action: 'Seek urgent medical evaluation. Avoid activities that could cause injury.' },
      { direction: 'low', value: 100, unit: '×10⁹/L', severity: 'warning', message: 'Low platelet count — increased bleeding risk with trauma or surgery.', action: 'See your clinician for evaluation.' },
      { direction: 'high', value: 1000, unit: '×10⁹/L', severity: 'critical', message: 'Extremely high platelet count — risk of clotting or bleeding complications.', action: 'Seek urgent hematology consultation.' },
      { direction: 'high', value: 500, unit: '×10⁹/L', severity: 'warning', message: 'Elevated platelet count may indicate reactive thrombocytosis or a myeloproliferative disorder.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'The number of platelets (thrombocytes) in your blood. Platelets are cell fragments that help your blood clot and prevent excessive bleeding.',
    whatResultMayMean: {
      high: 'Elevated platelets (thrombocytosis) can be reactive — triggered by infection, inflammation, iron deficiency, surgery, or blood loss — or primary, caused by bone marrow disorders such as essential thrombocythemia.',
      low: 'Low platelets (thrombocytopenia) may result from immune destruction (ITP), viral infections, liver disease, medications, bone marrow disorders, or increased consumption (as in DIC).',
    },
    commonNonDangerousReasons: {
      high: ['Recent infection or surgery', 'Iron deficiency', 'Acute inflammation', 'Strenuous exercise'],
      low: ['Viral illness (e.g., common cold, flu)', 'Pseudothrombocytopenia (EDTA-induced clumping — a lab artifact)', 'Pregnancy (mild decrease in third trimester)', 'Heavy alcohol use'],
    },
    whenItMatters: 'Platelet count is important before surgeries, in evaluating unexplained bruising or bleeding, and in monitoring bone marrow function.',
    dailyLifeActions: {
      high: [
        'Stay hydrated to support healthy blood flow',
        'If related to iron deficiency, address iron intake',
        'Avoid smoking, which increases clotting risk',
      ],
      low: [
        'Avoid contact sports or activities with high injury risk if platelets are significantly low',
        'Use a soft toothbrush and electric razor to minimize bleeding risk',
        'Avoid aspirin and NSAIDs unless directed by your clinician',
        'Limit alcohol consumption',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if platelet count is persistently above 450 ×10⁹/L, particularly if unexplained.',
      low: 'See a clinician if platelet count is below 100 ×10⁹/L, or immediately if below 50 ×10⁹/L or if you notice petechiae, easy bruising, or bleeding from gums or nose.',
    },
    preAnalyticalConfounders: [
      'EDTA-induced pseudothrombocytopenia (platelet clumping gives falsely low count)',
      'Delayed sample processing',
      'Difficult or traumatic blood draw',
      'Extreme cold exposure',
    ],
    medicationsAffecting: [
      'Heparin (can cause HIT — heparin-induced thrombocytopenia)',
      'Quinine (decrease)',
      'Valproic acid (decrease)',
      'Chemotherapy agents (decrease)',
      'Linezolid (decrease)',
      'Thiazide diuretics (decrease)',
    ],
    relatedBiomarkers: ['WBC', 'RBC', 'HGB', 'FE', 'FERRITIN'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'NEUT',
    name: 'Neutrophils',
    aliases: ['neutrophil count', 'ANC', 'absolute neutrophil count', 'PMN', 'polys', 'segs'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10⁹/L',
    alternativeUnits: ['%', 'cells/µL'],
    referenceRanges: [
      { sex: 'any', min: 2.0, max: 7.5, unit: '×10⁹/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 0.5, unit: '×10⁹/L', severity: 'critical', message: 'Severe neutropenia — extremely high risk of life-threatening infection.', action: 'Seek urgent medical care. Avoid all sources of infection.' },
      { direction: 'low', value: 1.0, unit: '×10⁹/L', severity: 'warning', message: 'Moderate neutropenia — increased susceptibility to bacterial infections.', action: 'Contact your clinician promptly.' },
      { direction: 'high', value: 20.0, unit: '×10⁹/L', severity: 'critical', message: 'Very high neutrophil count — may indicate severe infection, sepsis, or hematologic malignancy.', action: 'Seek immediate medical evaluation.' },
    ],
    whatItMeasures: 'The number of neutrophils, the most abundant type of white blood cell. Neutrophils are the first responders to bacterial infections and acute inflammation.',
    whatResultMayMean: {
      high: 'Elevated neutrophils (neutrophilia) most commonly indicate bacterial infection, acute stress, or inflammation. They can also rise with corticosteroid use, smoking, or rarely, chronic myeloid leukemia.',
      low: 'Low neutrophils (neutropenia) increase the risk of bacterial infections. Causes include viral infections, autoimmune neutropenia, bone marrow suppression, and benign ethnic neutropenia.',
    },
    commonNonDangerousReasons: {
      high: ['Acute bacterial infection', 'Physical or emotional stress', 'Corticosteroid use', 'Smoking', 'Pregnancy'],
      low: ['Benign ethnic neutropenia (common in people of African descent)', 'Recent viral infection', 'Mild cyclical variation'],
    },
    whenItMatters: 'Neutrophil count is critical when evaluating fever, infection risk in immunocompromised patients, and monitoring chemotherapy effects.',
    dailyLifeActions: {
      high: ['Address any underlying infection', 'Manage stress', 'If you smoke, consider cessation'],
      low: ['Practice meticulous hand hygiene', 'Avoid raw or undercooked foods if severely neutropenic', 'Stay up to date on vaccinations', 'Avoid crowded settings during flu season'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if neutrophils are above 10 ×10⁹/L without obvious cause, or above 20 ×10⁹/L urgently.',
      low: 'See a clinician if neutrophils are below 1.5 ×10⁹/L, or urgently if below 0.5 ×10⁹/L.',
    },
    preAnalyticalConfounders: ['Stress or exercise (transient increase)', 'Time of day (diurnal variation)', 'Smoking status'],
    medicationsAffecting: [
      'Corticosteroids (increase — demargination effect)',
      'G-CSF/filgrastim (increase)',
      'Chemotherapy (decrease)',
      'Clozapine (decrease — requires monitoring)',
      'Carbimazole/methimazole (decrease)',
    ],
    relatedBiomarkers: ['WBC', 'LYMPH', 'MONO', 'EOS', 'BASO', 'CRP'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'LYMPH',
    name: 'Lymphocytes',
    aliases: ['lymphocyte count', 'absolute lymphocyte count', 'ALC'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10⁹/L',
    alternativeUnits: ['%', 'cells/µL'],
    referenceRanges: [
      { sex: 'any', min: 1.0, max: 4.0, unit: '×10⁹/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 10.0, unit: '×10⁹/L', severity: 'critical', message: 'Markedly elevated lymphocytes — may indicate chronic lymphocytic leukemia or serious viral infection.', action: 'Seek prompt hematology evaluation.' },
      { direction: 'low', value: 0.5, unit: '×10⁹/L', severity: 'critical', message: 'Severe lymphopenia — significantly impaired immune function.', action: 'Seek urgent medical evaluation.' },
    ],
    whatItMeasures: 'The number of lymphocytes in your blood. Lymphocytes include T cells, B cells, and natural killer cells — key players in adaptive immunity, antibody production, and fighting viral infections.',
    whatResultMayMean: {
      high: 'Elevated lymphocytes (lymphocytosis) are most commonly caused by viral infections such as mononucleosis, influenza, or hepatitis. Persistent elevation may suggest chronic lymphocytic leukemia, especially in older adults.',
      low: 'Low lymphocytes (lymphopenia) can occur with HIV, autoimmune diseases, corticosteroid use, or during acute illness. Chronic lymphopenia increases susceptibility to infections.',
    },
    commonNonDangerousReasons: {
      high: ['Active viral infection (cold, flu, EBV)', 'Acute stress response', 'Post-vaccination immune activation'],
      low: ['Recent acute illness or surgery', 'High-dose corticosteroid use', 'Intense physical training'],
    },
    whenItMatters: 'Lymphocyte count is important for assessing immune status, investigating recurrent infections, and screening for hematologic malignancies.',
    dailyLifeActions: {
      high: ['Rest and allow recovery from any active infection', 'Stay hydrated', 'Monitor for resolution after illness clears'],
      low: ['Prioritize sleep and stress management to support immune function', 'Ensure adequate protein and micronutrient intake', 'Stay current on vaccinations'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if lymphocytes remain elevated above 5 ×10⁹/L for more than 2-3 weeks after any acute illness resolves.',
      low: 'See a clinician if lymphocytes are persistently below 1.0 ×10⁹/L, especially with recurrent infections.',
    },
    preAnalyticalConfounders: ['Acute stress (transient changes)', 'Exercise', 'Time of day', 'Recent vaccination'],
    medicationsAffecting: [
      'Corticosteroids (decrease)',
      'Chemotherapy (decrease)',
      'Immunosuppressants such as tacrolimus, mycophenolate (decrease)',
      'Rituximab (decrease B cells specifically)',
    ],
    relatedBiomarkers: ['WBC', 'NEUT', 'MONO'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'MONO',
    name: 'Monocytes',
    aliases: ['monocyte count', 'absolute monocyte count'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10⁹/L',
    alternativeUnits: ['%', 'cells/µL'],
    referenceRanges: [
      { sex: 'any', min: 0.2, max: 1.0, unit: '×10⁹/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 2.0, unit: '×10⁹/L', severity: 'warning', message: 'Elevated monocytes may indicate chronic infection, inflammatory condition, or hematologic disorder.', action: 'Discuss with your clinician for further workup.' },
    ],
    whatItMeasures: 'The number of monocytes, a type of white blood cell that matures into macrophages in tissues. They play a role in fighting chronic infections and clearing dead cells.',
    whatResultMayMean: {
      high: 'Elevated monocytes (monocytosis) may indicate chronic infections (tuberculosis, endocarditis), autoimmune diseases, chronic inflammatory conditions, or myeloproliferative disorders such as CMML.',
      low: 'Low monocytes (monocytopenia) are uncommon and may occur with bone marrow failure, corticosteroid use, or certain genetic conditions.',
    },
    commonNonDangerousReasons: {
      high: ['Recovery phase of an acute infection', 'Chronic mild inflammation', 'Stress response'],
      low: ['Acute infection (transient redistribution)', 'Corticosteroid use'],
    },
    whenItMatters: 'Monocyte count is useful when investigating chronic infections, unexplained inflammation, or suspected myeloproliferative disorders.',
    dailyLifeActions: {
      high: ['Support immune function with adequate nutrition and rest', 'Address any known chronic inflammatory conditions'],
      low: ['No specific lifestyle modifications are typically needed for isolated low monocytes'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if monocytes are persistently above 1.5 ×10⁹/L, particularly in the absence of an obvious cause.',
      low: 'Low monocytes alone rarely require follow-up unless accompanied by other abnormal counts.',
    },
    preAnalyticalConfounders: ['Exercise (transient changes)', 'Stress', 'Time of day'],
    medicationsAffecting: ['Corticosteroids (may decrease)', 'Chemotherapy (decrease)', 'G-CSF (may increase)'],
    relatedBiomarkers: ['WBC', 'NEUT', 'LYMPH', 'CRP', 'ESR'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'EOS',
    name: 'Eosinophils',
    aliases: ['eosinophil count', 'absolute eosinophil count', 'AEC'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10⁹/L',
    alternativeUnits: ['%', 'cells/µL'],
    referenceRanges: [
      { sex: 'any', min: 0.0, max: 0.5, unit: '×10⁹/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 1.5, unit: '×10⁹/L', severity: 'warning', message: 'Moderate eosinophilia — may indicate parasitic infection, allergic disease, or eosinophilic disorder.', action: 'Discuss with your clinician for evaluation.' },
      { direction: 'high', value: 5.0, unit: '×10⁹/L', severity: 'critical', message: 'Severe eosinophilia — risk of organ damage. May indicate hypereosinophilic syndrome.', action: 'Seek urgent medical evaluation.' },
    ],
    whatItMeasures: 'The number of eosinophils, white blood cells involved in fighting parasitic infections and mediating allergic responses.',
    whatResultMayMean: {
      high: 'Elevated eosinophils (eosinophilia) may indicate allergic conditions (asthma, eczema, drug allergy), parasitic infections, or eosinophilic disorders. Persistent marked elevation can damage the heart and other organs.',
      low: 'Low eosinophils are generally not clinically significant. They may decrease during acute stress or corticosteroid use.',
    },
    commonNonDangerousReasons: {
      high: ['Seasonal allergies (hay fever)', 'Asthma or eczema', 'Mild drug reaction', 'Recovery from infection'],
      low: [],
    },
    whenItMatters: 'Eosinophil count is important when evaluating allergic diseases, suspected parasitic infections, or unexplained organ damage.',
    dailyLifeActions: {
      high: [
        'Identify and manage allergic triggers if applicable',
        'If you have asthma or eczema, ensure your treatment plan is optimized',
        'If recently traveled to tropical regions, discuss parasitic screening with your clinician',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if eosinophils are above 1.0 ×10⁹/L, especially with cough, rash, or GI symptoms. Seek urgent care above 5.0 ×10⁹/L.',
      low: 'Low eosinophils alone do not require follow-up.',
    },
    preAnalyticalConfounders: ['Diurnal variation (lowest in the morning, peak at night)', 'Stress (acute decrease due to cortisol release)', 'Exercise'],
    medicationsAffecting: ['Corticosteroids (decrease)', 'Some antibiotics can cause drug-induced eosinophilia (increase)', 'IL-5 inhibitors such as mepolizumab (decrease)'],
    relatedBiomarkers: ['WBC', 'BASO', 'IgE (if available)'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'BASO',
    name: 'Basophils',
    aliases: ['basophil count', 'absolute basophil count'],
    category: 'hematology',
    specimenType: 'whole blood (EDTA)',
    defaultUnit: '×10⁹/L',
    alternativeUnits: ['%', 'cells/µL'],
    referenceRanges: [
      { sex: 'any', min: 0.0, max: 0.1, unit: '×10⁹/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 0.5, unit: '×10⁹/L', severity: 'warning', message: 'Elevated basophils may indicate allergic reaction, myeloproliferative disorder, or chronic myeloid leukemia.', action: 'Discuss with your clinician for hematologic evaluation.' },
    ],
    whatItMeasures: 'The number of basophils, the least common type of white blood cell. Basophils play a role in allergic reactions, inflammation, and antiparasitic defense by releasing histamine and other mediators.',
    whatResultMayMean: {
      high: 'Elevated basophils (basophilia) are uncommon and may indicate allergic reactions, hypothyroidism, chronic myeloid leukemia, or other myeloproliferative neoplasms.',
      low: 'Low basophils are normal and not clinically meaningful, as basophils make up less than 1% of circulating white cells.',
    },
    commonNonDangerousReasons: {
      high: ['Allergic reactions', 'Hypothyroidism', 'Ulcerative colitis'],
      low: [],
    },
    whenItMatters: 'Basophil count is primarily important when elevated, as persistent basophilia may be an early marker of myeloproliferative disorders.',
    dailyLifeActions: {
      high: ['Manage allergic triggers if applicable', 'Ensure thyroid function has been checked'],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if basophils are persistently elevated above 0.3 ×10⁹/L, especially with other CBC abnormalities.',
      low: 'Low basophils do not require follow-up.',
    },
    preAnalyticalConfounders: ['Stress (transient decrease)', 'Diurnal variation'],
    medicationsAffecting: ['Corticosteroids (decrease)', 'Estrogens (may increase)'],
    relatedBiomarkers: ['WBC', 'EOS', 'NEUT'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
];
