import type { BiomarkerKnowledge } from './types';

export const electrolyteBiomarkers: BiomarkerKnowledge[] = [
  {
    code: 'NA',
    name: 'Sodium',
    aliases: ['Na+', 'serum sodium', 'natrium'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mEq/L',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 136, max: 145, unit: 'mEq/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 120, unit: 'mEq/L', severity: 'critical', message: 'Severely low sodium — risk of cerebral edema, seizures, and coma.', action: 'Seek emergency medical care immediately.' },
      { direction: 'low', value: 130, unit: 'mEq/L', severity: 'warning', message: 'Low sodium (hyponatremia) — may cause confusion, nausea, and headache.', action: 'See your clinician for evaluation.' },
      { direction: 'high', value: 155, unit: 'mEq/L', severity: 'critical', message: 'Severely elevated sodium — risk of altered consciousness and seizures.', action: 'Seek emergency medical care.' },
      { direction: 'high', value: 148, unit: 'mEq/L', severity: 'warning', message: 'Elevated sodium (hypernatremia) usually indicates dehydration.', action: 'Increase fluid intake and see your clinician.' },
    ],
    whatItMeasures: 'The concentration of sodium ions in the blood. Sodium is the most abundant electrolyte in extracellular fluid and is critical for maintaining fluid balance, blood pressure, nerve impulse transmission, and muscle contraction.',
    whatResultMayMean: {
      high: 'Elevated sodium (hypernatremia) usually indicates water deficit — either insufficient water intake, excessive water loss (diabetes insipidus, diarrhea), or rarely, excess sodium intake. Symptoms include thirst, confusion, and irritability.',
      low: 'Low sodium (hyponatremia) may result from excess water relative to sodium. Causes include SIADH, heart failure, liver cirrhosis, kidney disease, diuretics, and excessive water drinking. Symptoms include nausea, headache, confusion, and in severe cases, seizures.',
    },
    commonNonDangerousReasons: {
      high: ['Dehydration from inadequate water intake', 'Excessive sweating', 'Diarrhea or vomiting'],
      low: [
        'Thiazide diuretic use',
        'Excessive water intake (psychogenic polydipsia or during endurance exercise)',
        'SSRI medications',
        'Mild hyponatremia during extreme heat with only water replacement (no electrolytes)',
      ],
    },
    whenItMatters: 'Sodium is critical for fluid balance assessment, medication management (especially diuretics), and monitoring in heart failure, liver disease, and kidney disease.',
    dailyLifeActions: {
      high: [
        'Increase water intake gradually',
        'Limit excessive salt intake',
        'Monitor thirst and urine color as hydration indicators',
      ],
      low: [
        'Restrict fluid intake if advised by your clinician (common in SIADH)',
        'Ensure adequate dietary sodium if on a very low-sodium diet',
        'If exercising for long periods, use electrolyte beverages rather than plain water',
        'Review medications with your clinician — thiazides and SSRIs are common culprits',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if sodium is above 146 mEq/L. Seek emergency care if above 155 mEq/L or with confusion, lethargy, or seizures.',
      low: 'See a clinician if sodium is below 134 mEq/L. Seek emergency care if below 125 mEq/L or with confusion, seizures, or severe headache.',
    },
    preAnalyticalConfounders: [
      'Severe hyperglycemia (dilutional pseudohyponatremia — each 100 mg/dL glucose above normal lowers sodium by ~1.6 mEq/L)',
      'Severe hyperlipidemia or hyperproteinemia (pseudohyponatremia with indirect ion-selective electrodes)',
      'Hemolysis',
      'IV fluid contamination of sample',
    ],
    medicationsAffecting: [
      'Thiazide diuretics (decrease — most common medication cause of hyponatremia)',
      'SSRIs (decrease — SIADH)',
      'Carbamazepine (decrease — SIADH)',
      'Desmopressin (decrease)',
      'Lithium (may cause diabetes insipidus — increase sodium)',
      'IV normal saline (increase)',
      'Hypertonic saline (increase)',
    ],
    relatedBiomarkers: ['K', 'CL', 'CO2', 'CREAT', 'BUN', 'GLU'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'K',
    name: 'Potassium',
    aliases: ['K+', 'serum potassium', 'kalium'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mEq/L',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 3.5, max: 5.0, unit: 'mEq/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 6.0, unit: 'mEq/L', severity: 'critical', message: 'Dangerously high potassium — risk of fatal cardiac arrhythmia.', action: 'Seek emergency medical care immediately. An ECG is urgently needed.' },
      { direction: 'high', value: 5.5, unit: 'mEq/L', severity: 'warning', message: 'Elevated potassium — risk of cardiac conduction abnormalities.', action: 'See your clinician promptly. Confirm with repeat sample (rule out hemolysis).' },
      { direction: 'low', value: 2.5, unit: 'mEq/L', severity: 'critical', message: 'Severely low potassium — risk of dangerous cardiac arrhythmia and muscle paralysis.', action: 'Seek emergency medical care.' },
      { direction: 'low', value: 3.0, unit: 'mEq/L', severity: 'warning', message: 'Low potassium — risk of muscle weakness, cramps, and cardiac arrhythmias.', action: 'See your clinician for potassium replacement and investigation.' },
    ],
    whatItMeasures: 'The concentration of potassium ions in the blood. Potassium is the most abundant intracellular electrolyte and is critical for cardiac muscle function, nerve transmission, and fluid balance. Even small changes can have profound cardiac effects.',
    whatResultMayMean: {
      high: 'Elevated potassium (hyperkalemia) can be life-threatening due to cardiac arrhythmias. Causes include kidney disease (most common), potassium-sparing diuretics, ACE inhibitors/ARBs, tissue breakdown (rhabdomyolysis, tumor lysis), and adrenal insufficiency.',
      low: 'Low potassium (hypokalemia) can cause muscle weakness, cramping, fatigue, and dangerous cardiac arrhythmias. Common causes include diuretics, vomiting/diarrhea, and inadequate dietary intake.',
    },
    commonNonDangerousReasons: {
      high: [
        'Hemolysis of sample (most common cause of falsely high potassium — the specimen should be re-drawn)',
        'Fist clenching during blood draw',
        'Prolonged tourniquet time',
        'Difficult blood draw with cell damage',
      ],
      low: [
        'Diarrhea or vomiting',
        'Diuretic use (especially thiazides and loop diuretics)',
        'Excessive sweating',
        'Low dietary intake',
      ],
    },
    whenItMatters: 'Potassium is one of the most critical electrolytes to monitor because of its direct effect on cardiac rhythm. It must be checked regularly in patients on diuretics, ACE inhibitors, ARBs, or with kidney disease.',
    dailyLifeActions: {
      high: [
        'Reduce high-potassium foods if advised by your clinician: bananas, oranges, potatoes, tomatoes, spinach, beans',
        'Avoid salt substitutes that contain potassium chloride',
        'Stay hydrated to support kidney potassium excretion',
        'Review supplements — some contain potassium',
      ],
      low: [
        'Eat potassium-rich foods: bananas, oranges, avocados, potatoes, sweet potatoes, spinach, beans, yogurt',
        'Stay hydrated, especially if experiencing diarrhea or vomiting',
        'If on diuretics, ask your clinician about potassium supplementation',
        'Coconut water is a natural source of potassium',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician promptly if potassium is above 5.0 mEq/L. Seek emergency care if above 6.0 mEq/L or with palpitations, chest pain, or muscle weakness.',
      low: 'See a clinician if potassium is below 3.5 mEq/L. Seek urgent care if below 3.0 mEq/L or with muscle weakness, cramps, or palpitations.',
    },
    preAnalyticalConfounders: [
      'Hemolysis (most common cause of spuriously elevated potassium — releases intracellular potassium)',
      'Prolonged tourniquet with fist clenching (falsely elevates)',
      'Pneumatic tube transport of sample (may cause hemolysis)',
      'Delayed sample processing (potassium leaks out of cells over time)',
      'Extreme thrombocytosis or leukocytosis (potassium released during clotting in serum)',
    ],
    medicationsAffecting: [
      'ACE inhibitors and ARBs (increase)',
      'Potassium-sparing diuretics — spironolactone, amiloride, triamterene (increase)',
      'NSAIDs (increase by reducing renal excretion)',
      'Trimethoprim (increase)',
      'Heparin (may increase by reducing aldosterone)',
      'Loop diuretics — furosemide, bumetanide (decrease)',
      'Thiazide diuretics (decrease)',
      'Insulin (shifts potassium intracellularly — decrease)',
      'Beta-2 agonists — albuterol (shift potassium intracellularly — decrease)',
      'Corticosteroids (decrease due to mineralocorticoid effect)',
    ],
    relatedBiomarkers: ['NA', 'CL', 'CO2', 'MG', 'CREAT', 'EGFR'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'CL',
    name: 'Chloride',
    aliases: ['Cl-', 'serum chloride'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mEq/L',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 98, max: 106, unit: 'mEq/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 115, unit: 'mEq/L', severity: 'critical', message: 'Severely elevated chloride may indicate dehydration or renal tubular acidosis.', action: 'Seek medical evaluation.' },
      { direction: 'low', value: 90, unit: 'mEq/L', severity: 'warning', message: 'Low chloride may indicate metabolic alkalosis, vomiting, or diuretic use.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'The concentration of chloride ions in the blood. Chloride works with sodium and bicarbonate to maintain fluid balance, blood volume, and acid-base equilibrium.',
    whatResultMayMean: {
      high: 'Elevated chloride (hyperchloremia) often accompanies dehydration or non-anion-gap metabolic acidosis (renal tubular acidosis, diarrhea, saline administration).',
      low: 'Low chloride (hypochloremia) usually accompanies metabolic alkalosis from vomiting, nasogastric suction, or diuretic use.',
    },
    commonNonDangerousReasons: {
      high: ['Dehydration', 'Excessive normal saline infusion', 'Diarrhea (loss of bicarbonate)'],
      low: ['Vomiting (loss of HCl from stomach)', 'Diuretic use', 'Excessive sweating'],
    },
    whenItMatters: 'Chloride is interpreted alongside sodium, potassium, and bicarbonate as part of the basic metabolic panel. It is particularly useful for acid-base assessment via the anion gap calculation.',
    dailyLifeActions: {
      high: ['Stay well-hydrated', 'Address underlying cause of dehydration or diarrhea'],
      low: ['Replace lost fluids with balanced electrolyte solutions', 'Address underlying vomiting or diuretic issues with your clinician'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if chloride is above 108 mEq/L, especially with abnormal sodium or bicarbonate.',
      low: 'See a clinician if chloride is below 96 mEq/L, especially with persistent vomiting or diuretic use.',
    },
    preAnalyticalConfounders: ['Dehydration', 'IV fluid composition', 'Hemolysis (minor effect)'],
    medicationsAffecting: [
      'Normal saline infusion (increase)',
      'Loop and thiazide diuretics (decrease)',
      'Corticosteroids (may decrease)',
      'Acetazolamide (increase — promotes bicarbonate loss)',
    ],
    relatedBiomarkers: ['NA', 'K', 'CO2'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'CO2',
    name: 'Bicarbonate / CO2',
    aliases: ['HCO3', 'bicarbonate', 'total CO2', 'tCO2', 'carbon dioxide'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mEq/L',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 22, max: 29, unit: 'mEq/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 15, unit: 'mEq/L', severity: 'critical', message: 'Severely low bicarbonate indicates significant metabolic acidosis.', action: 'Seek urgent medical evaluation.' },
      { direction: 'low', value: 18, unit: 'mEq/L', severity: 'warning', message: 'Low bicarbonate suggests metabolic acidosis.', action: 'Discuss with your clinician.' },
      { direction: 'high', value: 35, unit: 'mEq/L', severity: 'warning', message: 'Elevated bicarbonate suggests metabolic alkalosis.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'The level of bicarbonate in the blood, which is the main buffer system regulating acid-base balance. Total CO2 on a metabolic panel primarily reflects bicarbonate concentration.',
    whatResultMayMean: {
      high: 'Elevated bicarbonate (metabolic alkalosis) may result from vomiting, diuretic use, or excessive antacid intake. It can also be a compensatory response to chronic respiratory acidosis (e.g., COPD).',
      low: 'Low bicarbonate (metabolic acidosis) may indicate kidney disease, diabetic ketoacidosis, lactic acidosis, diarrhea, or certain toxin ingestions (methanol, ethylene glycol).',
    },
    commonNonDangerousReasons: {
      high: ['Chronic vomiting', 'Diuretic use', 'Excessive antacid or baking soda use'],
      low: ['Chronic diarrhea', 'Strenuous exercise (lactic acid)', 'Early kidney disease'],
    },
    whenItMatters: 'Bicarbonate is critical for acid-base assessment and is essential in evaluating diabetic ketoacidosis, kidney disease, respiratory conditions, and unexplained electrolyte abnormalities.',
    dailyLifeActions: {
      high: ['Address underlying cause (vomiting, antacid overuse)', 'Stay hydrated'],
      low: ['If related to diarrhea, maintain hydration with electrolyte solutions', 'If diabetic, monitor blood sugar closely and follow your diabetes management plan'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if CO2 is above 30 mEq/L with symptoms or other electrolyte abnormalities.',
      low: 'See a clinician if CO2 is below 20 mEq/L. Seek urgent care if below 15 mEq/L, especially with rapid breathing, confusion, or in the context of diabetes.',
    },
    preAnalyticalConfounders: [
      'Exposure to air (CO2 escapes from the sample, falsely lowering the value)',
      'Delayed processing',
      'Venous vs. arterial sample (arterial blood gas is more accurate for acid-base assessment)',
    ],
    medicationsAffecting: [
      'Loop and thiazide diuretics (increase — metabolic alkalosis)',
      'Acetazolamide (decrease — promotes bicarbonate excretion)',
      'Metformin (may decrease — lactic acidosis risk)',
      'Topiramate (decrease — carbonic anhydrase inhibitor)',
      'Antacids (increase if taken excessively)',
    ],
    relatedBiomarkers: ['NA', 'K', 'CL', 'BUN', 'CREAT', 'GLU'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'CA',
    name: 'Calcium',
    aliases: ['Ca', 'serum calcium', 'total calcium', 'Ca2+'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 8.5, max: 10.5, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 14.0, unit: 'mg/dL', severity: 'critical', message: 'Severe hypercalcemia — risk of cardiac arrhythmia, coma, and death.', action: 'Seek emergency medical care immediately.' },
      { direction: 'high', value: 11.0, unit: 'mg/dL', severity: 'warning', message: 'Elevated calcium — may indicate hyperparathyroidism or malignancy.', action: 'See your clinician for PTH measurement and further evaluation.' },
      { direction: 'low', value: 7.0, unit: 'mg/dL', severity: 'critical', message: 'Severely low calcium — risk of tetany, seizures, and cardiac arrest.', action: 'Seek emergency medical care.' },
      { direction: 'low', value: 8.0, unit: 'mg/dL', severity: 'warning', message: 'Low calcium may cause muscle cramps, tingling, and weakness.', action: 'See your clinician for evaluation.' },
    ],
    whatItMeasures: 'The total calcium level in the blood. About 50% is bound to albumin, 40% is ionized (biologically active), and 10% is complexed to anions. Calcium is essential for bone health, muscle contraction, nerve function, and blood clotting.',
    whatResultMayMean: {
      high: 'Elevated calcium (hypercalcemia) is most commonly caused by primary hyperparathyroidism or malignancy. Other causes include vitamin D excess, sarcoidosis, thiazide diuretics, and immobilization. Symptoms include fatigue, constipation, nausea, confusion, and kidney stones.',
      low: 'Low calcium (hypocalcemia) may result from vitamin D deficiency, hypoparathyroidism, chronic kidney disease, or low albumin (pseudohypocalcemia). Symptoms include muscle cramps, tingling, and in severe cases, seizures.',
    },
    commonNonDangerousReasons: {
      high: ['Mild primary hyperparathyroidism (common, usually benign)', 'Thiazide diuretic use', 'Excess calcium or vitamin D supplementation', 'Dehydration'],
      low: ['Low albumin (pseudohypocalcemia — ionized calcium may be normal)', 'Vitamin D deficiency', 'Chronic kidney disease'],
    },
    whenItMatters: 'Calcium is important for evaluating bone health, kidney stones, muscle symptoms, and suspected endocrine disorders. Always correct for albumin level or check ionized calcium.',
    dailyLifeActions: {
      high: [
        'Stay well-hydrated (at least 2-3 liters of water daily)',
        'Avoid excess calcium and vitamin D supplements',
        'Limit dairy intake if calcium is significantly elevated',
        'Stay active to reduce bone resorption from immobility',
      ],
      low: [
        'Ensure adequate calcium intake: dairy products, fortified plant milks, canned sardines with bones, leafy greens',
        'Ensure adequate vitamin D, which is necessary for calcium absorption',
        'Consider calcium supplementation as directed by your clinician (500-600 mg at a time, with food)',
        'Limit excess phosphate-rich processed foods, which can lower calcium',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if calcium is above 10.5 mg/dL for PTH measurement. Seek urgent evaluation if above 12 mg/dL or with symptoms.',
      low: 'See a clinician if calcium is below 8.5 mg/dL (corrected for albumin). Seek urgent care if below 7.5 mg/dL or with tetany, numbness, or seizures.',
    },
    preAnalyticalConfounders: [
      'Low albumin (falsely lowers total calcium — correct with formula: corrected Ca = measured Ca + 0.8 × (4.0 - albumin))',
      'Prolonged tourniquet (falsely elevates by concentrating proteins)',
      'Dehydration (falsely elevates)',
      'EDTA tube contamination (chelates calcium — drastically falsely low)',
    ],
    medicationsAffecting: [
      'Thiazide diuretics (increase)',
      'Lithium (increase — stimulates PTH)',
      'Calcium supplements (increase)',
      'Vitamin D supplements (increase)',
      'Loop diuretics — furosemide (decrease)',
      'Bisphosphonates (decrease — intended effect in hypercalcemia)',
      'Calcitonin (decrease)',
      'Corticosteroids (may decrease)',
      'Anticonvulsants (may decrease via vitamin D metabolism)',
    ],
    relatedBiomarkers: ['ALB', 'PHOS', 'MG', 'VITD', 'ALP', 'CREAT'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'MG',
    name: 'Magnesium',
    aliases: ['Mg', 'serum magnesium', 'Mg2+'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L', 'mEq/L'],
    referenceRanges: [
      { sex: 'any', min: 1.7, max: 2.2, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 4.0, unit: 'mg/dL', severity: 'critical', message: 'Severely elevated magnesium — risk of cardiac arrest, respiratory failure, and loss of deep tendon reflexes.', action: 'Seek emergency medical care.' },
      { direction: 'low', value: 1.0, unit: 'mg/dL', severity: 'critical', message: 'Severely low magnesium — risk of cardiac arrhythmias and seizures.', action: 'Seek urgent medical evaluation for IV magnesium replacement.' },
      { direction: 'low', value: 1.5, unit: 'mg/dL', severity: 'warning', message: 'Low magnesium may cause muscle cramps, weakness, and cardiac irritability.', action: 'See your clinician for supplementation.' },
    ],
    whatItMeasures: 'The concentration of magnesium in the blood. Magnesium is essential for over 300 enzymatic reactions, including energy production, protein synthesis, muscle and nerve function, blood sugar control, and blood pressure regulation.',
    whatResultMayMean: {
      high: 'Elevated magnesium (hypermagnesemia) is almost always caused by magnesium-containing medications (antacids, laxatives) in the setting of kidney failure. Symptoms include nausea, weakness, low blood pressure, and at very high levels, cardiac arrest.',
      low: 'Low magnesium (hypomagnesemia) is very common and often underdiagnosed. It can cause muscle cramps, tremor, fatigue, arrhythmias, and can worsen hypokalemia and hypocalcemia. Causes include poor diet, alcohol use, diuretics, and GI losses.',
    },
    commonNonDangerousReasons: {
      high: ['Magnesium supplement overuse in persons with normal kidney function (rare)'],
      low: [
        'Inadequate dietary intake (processed food diet)',
        'Alcohol consumption',
        'Diuretic use (loop and thiazide)',
        'Proton pump inhibitor use (long-term)',
        'Chronic diarrhea',
        'Excessive sweating',
        'Diabetes (renal magnesium wasting)',
      ],
    },
    whenItMatters: 'Magnesium is important in evaluating muscle cramps, arrhythmias, seizures, and refractory hypokalemia or hypocalcemia (which cannot be corrected without first correcting magnesium).',
    dailyLifeActions: {
      high: ['Stop magnesium-containing supplements, antacids, and laxatives', 'Ensure kidney function is adequate'],
      low: [
        'Eat magnesium-rich foods: dark leafy greens, nuts (almonds, cashews), seeds (pumpkin seeds), dark chocolate, avocado, legumes, whole grains',
        'Consider magnesium supplementation (glycinate or citrate forms are well-absorbed)',
        'Limit alcohol, which depletes magnesium',
        'Discuss with your clinician if on long-term PPI therapy, which impairs magnesium absorption',
        'Epsom salt baths may provide modest transdermal magnesium absorption',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if magnesium is above 2.5 mg/dL, especially with kidney disease. Seek emergency care above 4.0 mg/dL.',
      low: 'See a clinician if magnesium is below 1.7 mg/dL, especially with muscle cramps, tremor, or palpitations.',
    },
    preAnalyticalConfounders: [
      'Serum magnesium reflects only 1% of total body magnesium — levels may be normal despite total body depletion',
      'Hemolysis (falsely elevated — red cells contain more magnesium than serum)',
      'Prolonged tourniquet use',
    ],
    medicationsAffecting: [
      'Magnesium supplements and magnesium-containing antacids/laxatives (increase)',
      'Loop diuretics — furosemide (decrease)',
      'Thiazide diuretics (decrease)',
      'Proton pump inhibitors — long-term use (decrease absorption)',
      'Aminoglycosides (decrease — renal wasting)',
      'Cisplatin (decrease — renal wasting)',
      'Cyclosporine and tacrolimus (decrease)',
      'Amphotericin B (decrease)',
      'Digoxin (hypomagnesemia worsens digoxin toxicity)',
    ],
    relatedBiomarkers: ['CA', 'K', 'PHOS', 'CREAT'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'PHOS',
    name: 'Phosphate',
    aliases: ['phosphorus', 'serum phosphate', 'inorganic phosphorus', 'PO4'],
    category: 'electrolyte',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: 2.5, max: 4.5, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 7.0, unit: 'mg/dL', severity: 'critical', message: 'Severely elevated phosphate — risk of calcium-phosphate deposition in soft tissues and acute kidney injury.', action: 'Seek urgent medical evaluation.' },
      { direction: 'low', value: 1.0, unit: 'mg/dL', severity: 'critical', message: 'Severely low phosphate — risk of respiratory failure, cardiac dysfunction, and rhabdomyolysis.', action: 'Seek urgent medical care.' },
    ],
    whatItMeasures: 'The concentration of inorganic phosphate in the blood. Phosphate is essential for energy production (ATP), bone mineralization, DNA/RNA structure, and acid-base buffering. About 85% of body phosphate is in bones.',
    whatResultMayMean: {
      high: 'Elevated phosphate (hyperphosphatemia) is most commonly caused by chronic kidney disease (impaired excretion). Other causes include hypoparathyroidism, tumor lysis syndrome, and rhabdomyolysis. High phosphate promotes vascular calcification.',
      low: 'Low phosphate (hypophosphatemia) may result from refeeding syndrome, vitamin D deficiency, hyperparathyroidism, alcoholism, or phosphate-binding antacids. Severe hypophosphatemia can cause muscle weakness and respiratory failure.',
    },
    commonNonDangerousReasons: {
      high: ['Kidney disease (reduced excretion)', 'Excessive dairy or phosphate-additive intake', 'Hemolysis in sample', 'Non-fasting sample (slight postprandial increase)'],
      low: ['Antacid overuse (phosphate binders)', 'Alcoholism', 'Refeeding after prolonged fasting', 'Vitamin D deficiency'],
    },
    whenItMatters: 'Phosphate is important in evaluating bone disorders, kidney disease (CKD-mineral bone disease), refeeding syndrome, and unexplained muscle weakness.',
    dailyLifeActions: {
      high: [
        'Limit high-phosphate foods: processed foods (phosphate additives), cola drinks, dairy, organ meats',
        'Read food labels for phosphate additives (sodium phosphate, phosphoric acid)',
        'Take phosphate binders with meals if prescribed by your clinician',
      ],
      low: [
        'Include phosphate-rich foods: dairy, meat, fish, nuts, beans, whole grains',
        'Address underlying vitamin D deficiency if present',
        'Avoid excessive antacid use',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if phosphate is above 5.0 mg/dL, especially with kidney disease.',
      low: 'See a clinician if phosphate is below 2.0 mg/dL. Seek urgent care below 1.0 mg/dL.',
    },
    preAnalyticalConfounders: [
      'Hemolysis (falsely elevated — red cells contain much more phosphate than serum)',
      'Non-fasting sample (slight increase after meals)',
      'Diurnal variation (lower in the morning)',
      'Delayed sample processing (phosphate leaks from cells)',
    ],
    medicationsAffecting: [
      'Phosphate binders — calcium acetate, sevelamer, lanthanum (decrease)',
      'Vitamin D (may increase phosphate absorption)',
      'Antacids containing aluminum or calcium (decrease)',
      'Insulin (shifts phosphate intracellularly — decrease)',
      'IV glucose (decrease — insulin response shifts phosphate)',
      'Bisphosphonates (may decrease)',
    ],
    relatedBiomarkers: ['CA', 'VITD', 'ALP', 'CREAT', 'EGFR'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
];
