import type { BiomarkerKnowledge } from './types';

export const hormoneBiomarkers: BiomarkerKnowledge[] = [
  {
    code: 'TESTO',
    name: 'Testosterone (Total)',
    aliases: ['total testosterone', 'testosterone', 'serum testosterone'],
    category: 'hormone',
    specimenType: 'serum',
    defaultUnit: 'ng/dL',
    alternativeUnits: ['nmol/L'],
    referenceRanges: [
      { sex: 'male', min: 264, max: 916, unit: 'ng/dL', source: 'Endocrine Society 2018' },
      { sex: 'female', min: 15, max: 70, unit: 'ng/dL', source: 'Endocrine Society 2018' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 200, unit: 'ng/dL', severity: 'warning', message: 'Low testosterone in males may indicate hypogonadism. Symptoms may include fatigue, low libido, and decreased muscle mass.', action: 'Confirm with a repeat early morning sample and discuss with your clinician.' },
    ],
    whatItMeasures: 'The total amount of testosterone in the blood, including both protein-bound and free (bioavailable) fractions. In males, testosterone is primarily produced by the testes. In females, smaller amounts are produced by the ovaries and adrenal glands.',
    whatResultMayMean: {
      high: 'In males, elevated testosterone may indicate exogenous androgen use (injections, gels), adrenal tumors, or testicular tumors. In females, elevated testosterone may indicate PCOS, congenital adrenal hyperplasia, or ovarian tumors.',
      low: 'In males, low testosterone (hypogonadism) may cause fatigue, decreased libido, erectile dysfunction, reduced muscle mass, increased body fat, mood changes, and bone loss. Causes include primary testicular failure, pituitary disorders, aging, obesity, and chronic illness.',
    },
    commonNonDangerousReasons: {
      high: ['Testosterone replacement therapy', 'Anabolic steroid use', 'PCOS in women'],
      low: [
        'Normal aging in men (gradual decline after age 30)',
        'Obesity (adipose tissue converts testosterone to estrogen)',
        'Sleep deprivation',
        'Chronic stress (elevated cortisol suppresses testosterone)',
        'Opioid use',
        'Acute illness',
        'Blood draw in the afternoon (testosterone peaks in the early morning)',
      ],
    },
    whenItMatters: 'Testosterone testing is indicated for symptoms of hypogonadism in men (fatigue, low libido, erectile dysfunction) and hyperandrogenism in women (hirsutism, acne, menstrual irregularity, infertility).',
    dailyLifeActions: {
      high: [
        'In women with PCOS, weight management and regular exercise may help lower androgen levels',
        'Avoid anabolic steroids or unauthorized testosterone products',
      ],
      low: [
        'Maintain a healthy weight — obesity is a major driver of low testosterone in men',
        'Exercise regularly, especially resistance training, which may help support testosterone levels',
        'Prioritize sleep quality and duration (7-9 hours per night)',
        'Manage chronic stress',
        'Ensure adequate vitamin D and zinc intake',
        'Limit alcohol consumption, which can suppress testosterone production',
      ],
    },
    whenToSeeDoctor: {
      high: 'In women: see a clinician if testosterone is elevated with hirsutism, acne, or irregular periods. In men: discuss with your clinician if not on replacement therapy.',
      low: 'In men: see a clinician if total testosterone is below 300 ng/dL on two early morning samples, especially with symptoms.',
    },
    preAnalyticalConfounders: [
      'Time of day (testosterone peaks between 7-10 AM — morning draw is essential for accurate assessment)',
      'Sleep quality (poor sleep lowers testosterone)',
      'Acute illness (transient suppression)',
      'Obesity (lowers SHBG and total testosterone)',
      'Fasting state (fasting may increase testosterone slightly)',
    ],
    medicationsAffecting: [
      'Exogenous testosterone (increase)',
      'Opioids (decrease — suppress GnRH)',
      'Corticosteroids (decrease)',
      'Ketoconazole (decrease — inhibits steroidogenesis)',
      'Spironolactone (antiandrogen effect)',
      'GnRH agonists (decrease after initial flare)',
      'Clomiphene (increase — used therapeutically in men)',
      'Oral contraceptives in women (decrease free testosterone by increasing SHBG)',
    ],
    relatedBiomarkers: ['ESTRADIOL', 'DHEAS', 'CORTISOL'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'ESTRADIOL',
    name: 'Estradiol',
    aliases: ['E2', 'estradiol', '17-beta-estradiol'],
    category: 'hormone',
    specimenType: 'serum',
    defaultUnit: 'pg/mL',
    alternativeUnits: ['pmol/L'],
    referenceRanges: [
      { sex: 'male', min: 10, max: 40, unit: 'pg/mL', source: 'Endocrine Society' },
      { sex: 'female', min: 15, max: 350, unit: 'pg/mL', source: 'AACE (varies widely by menstrual phase: follicular 20-150, ovulatory 100-400, luteal 40-200, postmenopausal <20)' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 80, unit: 'pg/mL', severity: 'warning', message: 'Elevated estradiol in males may indicate aromatase excess, liver disease, or estrogen-producing tumor.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'The most potent and abundant estrogen in the body. In premenopausal women, estradiol is primarily produced by the ovaries and fluctuates throughout the menstrual cycle. In men, it is produced by conversion of testosterone via aromatase enzyme, mainly in fat tissue.',
    whatResultMayMean: {
      high: 'In women, levels vary widely by cycle phase — context is essential. In men, elevated estradiol may indicate obesity (increased aromatization), liver disease (decreased clearance), or exogenous estrogen exposure. Symptoms may include gynecomastia and sexual dysfunction.',
      low: 'In premenopausal women, low estradiol may indicate ovarian insufficiency, hypothalamic amenorrhea, or menopause. In postmenopausal women, low estradiol is expected.',
    },
    commonNonDangerousReasons: {
      high: ['Premenopausal women during ovulation (physiologic peak)', 'Obesity in men (increased aromatization)', 'Hormone replacement therapy', 'Pregnancy'],
      low: ['Postmenopause (physiologic)', 'Low body fat / excessive exercise in women', 'Breastfeeding', 'Perimenopausal transition'],
    },
    whenItMatters: 'Estradiol is important for evaluating menstrual irregularity, infertility, menopausal symptoms, gynecomastia in men, and monitoring hormone therapy.',
    dailyLifeActions: {
      high: [
        'In men with elevated estradiol and obesity, weight loss may reduce aromatization and lower levels',
        'Limit alcohol, which impairs estrogen metabolism',
      ],
      low: [
        'In premenopausal women, ensure adequate body fat and caloric intake (excessive exercise and restrictive eating lower estradiol)',
        'Weight-bearing exercise may help support bone health when estrogen is low',
        'Discuss hormone replacement therapy with your clinician if experiencing menopausal symptoms',
        'Ensure adequate calcium and vitamin D for bone protection',
      ],
    },
    whenToSeeDoctor: {
      high: 'In men: see a clinician if estradiol is above 40 pg/mL with symptoms. In women: interpret in context of menstrual cycle phase.',
      low: 'In premenopausal women: see a clinician if estradiol is persistently low with missed periods, hot flashes, or infertility.',
    },
    preAnalyticalConfounders: [
      'Menstrual cycle phase in women (dramatic variation — must be correlated with cycle day)',
      'Time of day (less variation than testosterone, but morning is preferred)',
      'BMI (obesity increases estradiol in men)',
      'Biotin supplements (may interfere with some immunoassays)',
    ],
    medicationsAffecting: [
      'Oral contraceptives (suppress endogenous estradiol)',
      'Hormone replacement therapy (increase)',
      'Aromatase inhibitors — letrozole, anastrozole (decrease)',
      'Clomiphene (may increase via ovarian stimulation)',
      'Tamoxifen (blocks estrogen receptors but may increase levels)',
      'GnRH agonists (decrease after initial flare)',
    ],
    relatedBiomarkers: ['TESTO', 'FSH (if available)', 'LH (if available)'],
    evidenceTier: 2,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'CORTISOL',
    name: 'Cortisol (AM)',
    aliases: ['morning cortisol', 'serum cortisol', 'cortisol AM'],
    category: 'hormone',
    specimenType: 'serum',
    defaultUnit: 'µg/dL',
    alternativeUnits: ['nmol/L'],
    referenceRanges: [
      { sex: 'any', min: 6.0, max: 18.0, unit: 'µg/dL', source: 'Endocrine Society (8 AM sample)' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 3.0, unit: 'µg/dL', severity: 'critical', message: 'Very low morning cortisol may indicate adrenal insufficiency — risk of adrenal crisis.', action: 'Seek urgent endocrine evaluation. Do not stop corticosteroid medications abruptly.' },
      { direction: 'high', value: 25.0, unit: 'µg/dL', severity: 'warning', message: 'Elevated morning cortisol may indicate Cushing syndrome or severe stress.', action: 'Discuss further testing (24-hour urine cortisol, dexamethasone suppression test) with your clinician.' },
    ],
    whatItMeasures: 'The level of cortisol, the primary stress hormone produced by the adrenal glands. Cortisol follows a strong diurnal pattern — highest in the early morning (helping you wake up) and lowest around midnight. It regulates metabolism, immune function, blood pressure, and the stress response.',
    whatResultMayMean: {
      high: 'Elevated AM cortisol may indicate Cushing syndrome (excess cortisol from pituitary, adrenal, or ectopic sources), severe physiologic stress, or exogenous glucocorticoid use. A single high value is not diagnostic — dynamic testing is needed.',
      low: 'Low AM cortisol may indicate adrenal insufficiency (Addison disease or secondary from pituitary dysfunction). A morning cortisol below 3 µg/dL is strongly suggestive, while above 15 µg/dL essentially rules it out.',
    },
    commonNonDangerousReasons: {
      high: [
        'Acute physical or emotional stress at the time of blood draw',
        'Depression or severe anxiety',
        'Intense exercise',
        'Pregnancy (cortisol increases 2-3 fold)',
        'Oral contraceptive use (increases cortisol-binding globulin, raising total but not free cortisol)',
      ],
      low: [
        'Late morning or afternoon blood draw (cortisol naturally declines)',
        'Recent corticosteroid tapering (HPA axis suppression)',
        'Shift work or disrupted sleep-wake cycle',
      ],
    },
    whenItMatters: 'AM cortisol is a screening test for adrenal insufficiency and Cushing syndrome. It is indicated for unexplained fatigue, weight changes, hyperpigmentation, low blood pressure, recurrent infections, or Cushingoid features.',
    dailyLifeActions: {
      high: [
        'Practice stress management: meditation, deep breathing, regular exercise',
        'Ensure 7-9 hours of quality sleep',
        'Limit caffeine, which stimulates cortisol release',
        'Maintain regular meal timing and balanced nutrition',
        'Avoid overtraining if you exercise intensely',
      ],
      low: [
        'If on steroid medications, never stop them abruptly — taper only under medical supervision',
        'Wear a medical alert bracelet if diagnosed with adrenal insufficiency',
        'Carry emergency hydrocortisone if prescribed',
        'Stay hydrated and maintain adequate salt intake',
        'Avoid prolonged fasting',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if AM cortisol is above 20 µg/dL with Cushingoid features (weight gain, moon face, purple striae, easy bruising).',
      low: 'See a clinician urgently if AM cortisol is below 5 µg/dL with fatigue, dizziness, hypotension, or hyperpigmentation. Below 3 µg/dL strongly suggests adrenal insufficiency.',
    },
    preAnalyticalConfounders: [
      'Time of blood draw is critical — must be drawn between 7-9 AM for meaningful interpretation',
      'Acute stress or anxiety at the time of draw (falsely elevated)',
      'Oral contraceptives (increase cortisol-binding globulin, raising total cortisol)',
      'Pregnancy (physiologic increase)',
      'Shift work or jet lag (disrupted circadian rhythm)',
      'Sleep deprivation',
    ],
    medicationsAffecting: [
      'Exogenous glucocorticoids — prednisone, dexamethasone (suppress endogenous cortisol)',
      'Oral contraceptives (increase total cortisol via CBG increase)',
      'Ketoconazole (decreases cortisol — used therapeutically in Cushing)',
      'Megestrol acetate (glucocorticoid activity, suppresses cortisol)',
      'Opioids (may suppress HPA axis)',
      'Metyrapone (inhibits cortisol synthesis — used in testing)',
    ],
    relatedBiomarkers: ['DHEAS', 'TESTO', 'NA', 'K', 'GLU'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'DHEAS',
    name: 'DHEA-Sulfate',
    aliases: ['DHEA-S', 'dehydroepiandrosterone sulfate', 'DHEAS'],
    category: 'hormone',
    specimenType: 'serum',
    defaultUnit: 'µg/dL',
    alternativeUnits: ['µmol/L'],
    referenceRanges: [
      { sex: 'male', min: 80, max: 560, unit: 'µg/dL', ageMin: 18, ageMax: 50, source: 'Endocrine Society' },
      { sex: 'male', min: 30, max: 300, unit: 'µg/dL', ageMin: 50, source: 'Endocrine Society' },
      { sex: 'female', min: 35, max: 430, unit: 'µg/dL', ageMin: 18, ageMax: 50, source: 'Endocrine Society' },
      { sex: 'female', min: 20, max: 200, unit: 'µg/dL', ageMin: 50, source: 'Endocrine Society' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 700, unit: 'µg/dL', severity: 'warning', message: 'Markedly elevated DHEA-S may indicate an adrenal tumor (adenoma or carcinoma) or congenital adrenal hyperplasia.', action: 'Discuss adrenal imaging and further evaluation with your clinician.' },
      { direction: 'low', value: 20, unit: 'µg/dL', severity: 'warning', message: 'Very low DHEA-S may indicate adrenal insufficiency.', action: 'Discuss cortisol and adrenal function testing with your clinician.' },
    ],
    whatItMeasures: 'The level of DHEA-sulfate, the most abundant circulating steroid hormone produced almost exclusively by the adrenal glands. DHEA-S serves as a precursor for both androgens and estrogens. It declines steadily with age from a peak in the mid-20s.',
    whatResultMayMean: {
      high: 'Elevated DHEA-S may indicate congenital adrenal hyperplasia, adrenal tumors, PCOS (mild elevation), or adrenal Cushing syndrome. In women, it can cause hirsutism, acne, and virilization if markedly elevated.',
      low: 'Low DHEA-S may indicate adrenal insufficiency, hypopituitarism, or normal aging (levels decline 10-20% per decade after age 30).',
    },
    commonNonDangerousReasons: {
      high: ['PCOS (mild elevation)', 'Adrenal stress response', 'DHEA supplementation'],
      low: ['Normal aging (significant decline after age 30)', 'Chronic illness', 'Chronic corticosteroid use'],
    },
    whenItMatters: 'DHEA-S is useful for evaluating adrenal androgen excess (differentiating adrenal from ovarian sources of androgens) and screening for adrenal tumors when markedly elevated.',
    dailyLifeActions: {
      high: [
        'Avoid DHEA supplements if levels are already elevated',
        'In women with PCOS-related elevation, weight management may help',
      ],
      low: [
        'DHEA supplementation is not routinely recommended despite marketing claims — discuss with your clinician',
        'Manage chronic stress, which can deplete adrenal function',
        'Ensure adequate sleep and nutrition',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if DHEA-S is above the age-adjusted reference range, especially if markedly elevated (>600 µg/dL) to rule out adrenal tumor.',
      low: 'See a clinician if DHEA-S is very low for your age, especially with fatigue, low blood pressure, or other signs of adrenal insufficiency.',
    },
    preAnalyticalConfounders: [
      'Minimal diurnal variation (advantage — can be drawn at any time)',
      'Age (strong inverse correlation — must use age-appropriate reference ranges)',
      'DHEA supplements (will be elevated)',
      'Stress (may acutely elevate)',
    ],
    medicationsAffecting: [
      'DHEA supplements (increase)',
      'Corticosteroids (decrease — suppress adrenal function)',
      'Insulin sensitizers — metformin (may slightly decrease in PCOS)',
      'Oral contraceptives (may slightly decrease)',
      'Ketoconazole (decrease — inhibits steroidogenesis)',
    ],
    relatedBiomarkers: ['CORTISOL', 'TESTO', 'ESTRADIOL'],
    evidenceTier: 2,
    lastReviewed: '2026-03-01',
  },
];
