import type { BiomarkerKnowledge } from './types';

export const ironBiomarkers: BiomarkerKnowledge[] = [
  {
    code: 'FERRITIN',
    name: 'Ferritin',
    aliases: ['serum ferritin', 'ferritine'],
    category: 'iron',
    specimenType: 'serum',
    defaultUnit: 'ng/mL',
    alternativeUnits: ['µg/L', 'pmol/L'],
    referenceRanges: [
      { sex: 'male', min: 30, max: 400, unit: 'ng/mL', source: 'WHO/CLSI' },
      { sex: 'female', min: 15, max: 200, unit: 'ng/mL', source: 'WHO/CLSI', pregnancyCaveat: 'Ferritin normally decreases during pregnancy. Values below 30 ng/mL in pregnancy suggest depleted iron stores.' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 1000, unit: 'ng/mL', severity: 'critical', message: 'Very high ferritin may indicate hemochromatosis, liver disease, malignancy, or severe inflammation.', action: 'Seek prompt medical evaluation to determine the cause.' },
      { direction: 'high', value: 500, unit: 'ng/mL', severity: 'warning', message: 'Elevated ferritin — may reflect iron overload, inflammation, or liver disease.', action: 'Discuss with your clinician.' },
      { direction: 'low', value: 10, unit: 'ng/mL', severity: 'warning', message: 'Very low ferritin confirms iron deficiency.', action: 'See your clinician about iron supplementation.' },
    ],
    whatItMeasures: 'Ferritin is a protein that stores iron inside cells. Serum ferritin reflects total body iron stores. It is the most sensitive and specific early marker for iron deficiency.',
    whatResultMayMean: {
      high: 'Elevated ferritin may indicate iron overload (hemochromatosis), liver disease, chronic inflammation, infection, or malignancy. Ferritin is also an acute-phase reactant, meaning it rises with inflammation independently of iron status.',
      low: 'Low ferritin is highly specific for depleted iron stores and is the earliest marker of iron deficiency, often dropping before hemoglobin falls.',
    },
    commonNonDangerousReasons: {
      high: [
        'Acute or chronic inflammation (even mild)',
        'Alcohol consumption',
        'Metabolic syndrome or fatty liver',
        'Recent intense exercise',
        'Acute infection',
      ],
      low: [
        'Heavy menstrual periods',
        'Vegetarian or vegan diet',
        'Frequent blood donation',
        'Pregnancy',
        'Growth spurts in adolescents',
      ],
    },
    whenItMatters: 'Ferritin is the first-line test for evaluating suspected iron deficiency and is important for monitoring iron replacement therapy, investigating fatigue, hair loss, or restless legs.',
    dailyLifeActions: {
      high: [
        'Avoid iron supplements unless directed by your clinician',
        'Limit red meat intake if iron overload is confirmed',
        'Reduce alcohol consumption, which can worsen liver iron deposition',
        'Avoid vitamin C supplements with meals (enhances iron absorption)',
      ],
      low: [
        'Include heme iron sources such as red meat, poultry, and fish',
        'Include non-heme iron sources such as lentils, spinach, and fortified cereals',
        'Pair iron-rich meals with vitamin C (citrus, bell peppers) to enhance absorption',
        'Avoid tea, coffee, and calcium with iron-rich meals as they inhibit absorption',
        'Cook in cast iron cookware, which can add small amounts of iron to food',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if ferritin is above 500 ng/mL to rule out hemochromatosis, liver disease, or malignancy. Seek urgent evaluation above 1000 ng/mL.',
      low: 'See a clinician if ferritin is below 30 ng/mL, especially with fatigue, hair loss, or restless legs. Below 15 ng/mL is diagnostic of iron deficiency.',
    },
    preAnalyticalConfounders: [
      'Acute inflammation or infection (falsely elevated)',
      'Liver damage (falsely elevated due to ferritin release)',
      'Fasting vs. fed state (minor effect)',
      'Recent vigorous exercise',
      'Alcohol consumption',
    ],
    medicationsAffecting: [
      'Iron supplements (increase)',
      'Oral contraceptives (may slightly increase)',
      'Testosterone (increase erythropoiesis, may decrease stores)',
      'NSAIDs (may cause occult bleeding leading to decrease)',
    ],
    relatedBiomarkers: ['FE', 'TIBC', 'TSAT', 'TRANSFERRIN', 'HGB', 'MCV', 'RDW'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'FE',
    name: 'Serum Iron',
    aliases: ['iron', 'serum iron level', 'Fe'],
    category: 'iron',
    specimenType: 'serum',
    defaultUnit: 'µg/dL',
    alternativeUnits: ['µmol/L'],
    referenceRanges: [
      { sex: 'male', min: 65, max: 175, unit: 'µg/dL', source: 'CLSI' },
      { sex: 'female', min: 50, max: 170, unit: 'µg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 300, unit: 'µg/dL', severity: 'critical', message: 'Severely elevated serum iron — may indicate acute iron poisoning or hemochromatosis.', action: 'Seek urgent medical evaluation.' },
      { direction: 'low', value: 30, unit: 'µg/dL', severity: 'warning', message: 'Low serum iron suggests iron deficiency.', action: 'Discuss iron studies with your clinician.' },
    ],
    whatItMeasures: 'The amount of iron circulating in your blood, bound to the transport protein transferrin. Serum iron represents only a small fraction of total body iron.',
    whatResultMayMean: {
      high: 'Elevated serum iron may indicate hemochromatosis, iron supplementation overdose, hemolytic anemias (iron released from destroyed red cells), or liver damage.',
      low: 'Low serum iron may indicate iron deficiency from poor intake, blood loss, or chronic disease. However, serum iron alone is not reliable — it varies significantly throughout the day.',
    },
    commonNonDangerousReasons: {
      high: ['Recent iron supplement intake', 'Recent consumption of iron-rich meal', 'Morning blood draw (diurnal peak)'],
      low: ['Evening blood draw (diurnal trough)', 'Menstruation', 'Acute infection or inflammation'],
    },
    whenItMatters: 'Serum iron is best interpreted alongside TIBC and transferrin saturation as part of a complete iron panel. It is most useful when evaluating the cause of anemia.',
    dailyLifeActions: {
      high: ['Do not take iron supplements unless prescribed', 'Avoid excessive red meat or organ meats if iron overload is suspected'],
      low: ['Include iron-rich foods in your diet', 'Pair with vitamin C for better absorption', 'Discuss supplementation with your clinician'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if serum iron is above 200 µg/dL, particularly with elevated transferrin saturation.',
      low: 'See a clinician if serum iron is below 40 µg/dL with low ferritin, to confirm iron deficiency.',
    },
    preAnalyticalConfounders: [
      'Significant diurnal variation (highest in the morning, lowest in the evening)',
      'Recent iron-rich meal (falsely elevated)',
      'Oral iron supplements taken before the test (falsely elevated)',
      'Hemolyzed sample (falsely elevated)',
      'Acute inflammation (lowers serum iron independently of iron status)',
    ],
    medicationsAffecting: [
      'Iron supplements (increase)',
      'Oral contraceptives (may increase)',
      'Deferoxamine (decrease — iron chelator)',
      'Chloramphenicol (may increase)',
    ],
    relatedBiomarkers: ['FERRITIN', 'TIBC', 'TSAT', 'TRANSFERRIN', 'HGB'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'TRANSFERRIN',
    name: 'Transferrin',
    aliases: ['serum transferrin', 'siderophilin'],
    category: 'iron',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['g/L'],
    referenceRanges: [
      { sex: 'any', min: 200, max: 360, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 150, unit: 'mg/dL', severity: 'warning', message: 'Low transferrin may indicate chronic disease, liver disease, or protein malnutrition.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'Transferrin is the main protein that transports iron in the blood. It is produced by the liver and its level reflects both iron status and liver synthetic function.',
    whatResultMayMean: {
      high: 'Elevated transferrin usually indicates iron deficiency — the body increases production to capture more iron. It can also rise during pregnancy and with oral contraceptive use.',
      low: 'Low transferrin may indicate chronic disease, liver disease, nephrotic syndrome (protein loss), or malnutrition.',
    },
    commonNonDangerousReasons: {
      high: ['Iron deficiency from diet', 'Pregnancy', 'Oral contraceptive use'],
      low: ['Acute inflammation', 'Mild liver disease', 'Older age'],
    },
    whenItMatters: 'Transferrin helps distinguish iron deficiency anemia from anemia of chronic disease and supports calculation of transferrin saturation.',
    dailyLifeActions: {
      high: ['Address underlying iron deficiency with dietary changes or supplementation as directed'],
      low: ['Ensure adequate protein intake', 'Support liver health by limiting alcohol'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if transferrin is elevated with low ferritin, confirming iron deficiency requiring treatment.',
      low: 'See a clinician if transferrin is below 180 mg/dL to evaluate for liver disease or chronic illness.',
    },
    preAnalyticalConfounders: ['Inflammation (negative acute-phase reactant — decreases)', 'Liver disease', 'Nutritional status', 'Pregnancy (physiologic increase)'],
    medicationsAffecting: ['Oral contraceptives (increase)', 'Androgens (decrease)', 'Corticosteroids (may decrease)'],
    relatedBiomarkers: ['FE', 'FERRITIN', 'TIBC', 'TSAT'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'TSAT',
    name: 'Transferrin Saturation',
    aliases: ['TSAT', 'iron saturation', 'transferrin sat', '%saturation'],
    category: 'iron',
    specimenType: 'serum',
    defaultUnit: '%',
    referenceRanges: [
      { sex: 'male', min: 20, max: 50, unit: '%', source: 'CLSI' },
      { sex: 'female', min: 15, max: 50, unit: '%', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 60, unit: '%', severity: 'warning', message: 'Elevated transferrin saturation may indicate iron overload or hemochromatosis.', action: 'Discuss HFE gene testing with your clinician.' },
      { direction: 'low', value: 15, unit: '%', severity: 'warning', message: 'Low transferrin saturation suggests iron deficiency or iron-restricted erythropoiesis.', action: 'Review iron studies with your clinician.' },
    ],
    whatItMeasures: 'The percentage of transferrin binding sites that are occupied by iron. It is calculated as serum iron divided by TIBC, multiplied by 100. It reflects how much of the iron transport capacity is being used.',
    whatResultMayMean: {
      high: 'Elevated transferrin saturation (above 45-50%) raises suspicion for hemochromatosis or iron overload. Levels above 60% warrant genetic testing for hereditary hemochromatosis.',
      low: 'Low transferrin saturation (below 20%) indicates functional iron deficiency — the body does not have enough circulating iron for red cell production, even if ferritin may appear normal due to inflammation.',
    },
    commonNonDangerousReasons: {
      high: ['Recent iron supplement intake', 'Morning blood draw', 'Iron-rich meal before test'],
      low: ['Menstruation', 'Dietary iron insufficiency', 'Acute inflammation'],
    },
    whenItMatters: 'Transferrin saturation is a key screening test for hemochromatosis and helps distinguish iron deficiency from anemia of chronic disease.',
    dailyLifeActions: {
      high: ['Avoid iron supplements unless prescribed', 'Limit vitamin C supplements which enhance iron absorption', 'Discuss with your clinician about iron overload screening'],
      low: ['Optimize dietary iron intake', 'Enhance iron absorption with vitamin C-rich foods'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if transferrin saturation exceeds 45% on repeat testing, especially with elevated ferritin.',
      low: 'See a clinician if transferrin saturation is below 16% with symptoms of anemia.',
    },
    preAnalyticalConfounders: ['Diurnal variation of serum iron affects the calculation', 'Recent iron supplement or iron-rich meal', 'Inflammation'],
    medicationsAffecting: ['Iron supplements (increase)', 'Oral contraceptives (may affect by increasing transferrin)'],
    relatedBiomarkers: ['FE', 'TIBC', 'TRANSFERRIN', 'FERRITIN', 'HGB'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'TIBC',
    name: 'Total Iron-Binding Capacity',
    aliases: ['TIBC', 'total iron binding capacity'],
    category: 'iron',
    specimenType: 'serum',
    defaultUnit: 'µg/dL',
    alternativeUnits: ['µmol/L'],
    referenceRanges: [
      { sex: 'any', min: 250, max: 370, unit: 'µg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 450, unit: 'µg/dL', severity: 'warning', message: 'Elevated TIBC is consistent with iron deficiency.', action: 'Evaluate iron stores with ferritin and transferrin saturation.' },
      { direction: 'low', value: 200, unit: 'µg/dL', severity: 'warning', message: 'Low TIBC may indicate iron overload, chronic disease, or malnutrition.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'The total capacity of transferrin in the blood to bind iron. TIBC is an indirect measure of transferrin levels and reflects the availability of iron-binding sites.',
    whatResultMayMean: {
      high: 'Elevated TIBC indicates the body is producing more transferrin to capture scarce iron — strongly suggestive of iron deficiency.',
      low: 'Low TIBC may occur in iron overload (hemochromatosis), chronic inflammatory disease, liver disease, or malnutrition.',
    },
    commonNonDangerousReasons: {
      high: ['Iron deficiency from diet', 'Pregnancy', 'Oral contraceptive use'],
      low: ['Chronic inflammation', 'Older age', 'Mild liver disease'],
    },
    whenItMatters: 'TIBC is most useful as part of a complete iron panel and for calculating transferrin saturation. It helps distinguish iron deficiency (high TIBC) from anemia of chronic disease (low TIBC).',
    dailyLifeActions: {
      high: ['Increase dietary iron intake', 'Enhance iron absorption with vitamin C'],
      low: ['Ensure adequate protein and calorie intake', 'Limit alcohol if liver disease is a concern'],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if TIBC is elevated with low ferritin and low serum iron to initiate iron replacement therapy.',
      low: 'See a clinician if TIBC is low with elevated ferritin, to evaluate for iron overload or chronic disease.',
    },
    preAnalyticalConfounders: ['Inflammation (decreased as negative acute-phase response)', 'Liver disease', 'Nutritional status'],
    medicationsAffecting: ['Oral contraceptives (increase)', 'ACTH (decrease)', 'Corticosteroids (decrease)'],
    relatedBiomarkers: ['FE', 'FERRITIN', 'TSAT', 'TRANSFERRIN', 'HGB'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
];
