import type { BiomarkerKnowledge } from './types';

export const lipidBiomarkers: BiomarkerKnowledge[] = [
  {
    code: 'TC',
    name: 'Total Cholesterol',
    aliases: ['cholesterol', 'total cholesterol', 'TC'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: null, max: 200, unit: 'mg/dL', source: 'ATP III / AHA 2018' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 300, unit: 'mg/dL', severity: 'critical', message: 'Very high total cholesterol — significantly elevated cardiovascular risk. Consider familial hypercholesterolemia.', action: 'See your clinician urgently. Genetic lipid testing may be warranted.' },
      { direction: 'high', value: 240, unit: 'mg/dL', severity: 'warning', message: 'High total cholesterol — increased cardiovascular risk.', action: 'Discuss lipid-lowering strategies with your clinician.' },
    ],
    whatItMeasures: 'The total amount of cholesterol in your blood, including LDL, HDL, and VLDL. Cholesterol is a waxy substance essential for cell membranes, hormones, and bile acids, but excess levels increase cardiovascular risk.',
    whatResultMayMean: {
      high: 'Elevated total cholesterol increases the risk of atherosclerosis, heart attack, and stroke. However, total cholesterol alone is incomplete — the balance between LDL and HDL matters more. Very high levels (>300 mg/dL) may suggest familial hypercholesterolemia.',
      low: 'Very low total cholesterol (below 120 mg/dL) may be associated with liver disease, malnutrition, hyperthyroidism, or certain cancers. It can also occur with some medications.',
    },
    commonNonDangerousReasons: {
      high: [
        'Diet high in saturated and trans fats',
        'Sedentary lifestyle',
        'Genetic predisposition',
        'Hypothyroidism (untreated)',
        'Pregnancy (physiologic increase)',
        'Older age',
      ],
      low: [
        'Hyperthyroidism',
        'Very low-fat diet',
        'Statin use',
        'Liver disease',
      ],
    },
    whenItMatters: 'Total cholesterol is a useful screening test but should always be interpreted alongside the full lipid panel (LDL, HDL, triglycerides) for cardiovascular risk assessment.',
    dailyLifeActions: {
      high: [
        'Reduce saturated fat intake (limit red meat, full-fat dairy, fried foods)',
        'Eliminate trans fats (partially hydrogenated oils)',
        'Increase soluble fiber intake (oats, beans, lentils, fruits)',
        'Engage in regular aerobic exercise (at least 150 minutes per week)',
        'Include heart-healthy fats (olive oil, avocado, nuts, fatty fish)',
        'Maintain a healthy weight',
        'Consider plant stanols/sterols (2 g/day can lower LDL by 5-10%)',
      ],
      low: [
        'Ensure adequate caloric and fat intake',
        'Have thyroid function checked if not recently done',
        'Discuss with your clinician if cholesterol is below 120 mg/dL',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if total cholesterol is above 240 mg/dL for a comprehensive lipid panel and cardiovascular risk assessment. Seek urgent evaluation if above 300 mg/dL.',
      low: 'See a clinician if total cholesterol is below 120 mg/dL to evaluate for underlying causes.',
    },
    preAnalyticalConfounders: [
      'Fasting vs. non-fasting (total cholesterol is minimally affected, but fasting is preferred for full lipid panel)',
      'Posture during blood draw (standing increases values 5-10%)',
      'Acute illness (cholesterol drops during acute events)',
      'Seasonal variation (slightly higher in winter)',
      'Recent weight change',
    ],
    medicationsAffecting: [
      'Statins (decrease)',
      'Ezetimibe (decrease)',
      'PCSK9 inhibitors (decrease)',
      'Thiazide diuretics (may slightly increase)',
      'Corticosteroids (increase)',
      'Oral contraceptives (may increase)',
      'Beta-blockers (may increase triglycerides and slightly increase total cholesterol)',
    ],
    relatedBiomarkers: ['LDL', 'HDL', 'TRIG', 'NON_HDL'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'LDL',
    name: 'LDL Cholesterol',
    aliases: ['LDL-C', 'low-density lipoprotein cholesterol', 'bad cholesterol'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: null, max: 100, unit: 'mg/dL', source: 'AHA/ACC 2018 (optimal for average-risk adults)' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 190, unit: 'mg/dL', severity: 'critical', message: 'Very high LDL cholesterol — strongly consider familial hypercholesterolemia. High-intensity statin therapy is generally indicated.', action: 'See your clinician. Familial hypercholesterolemia screening may be appropriate.' },
      { direction: 'high', value: 160, unit: 'mg/dL', severity: 'warning', message: 'High LDL cholesterol — elevated cardiovascular risk.', action: 'Discuss lipid-lowering therapy with your clinician.' },
    ],
    whatItMeasures: 'The concentration of cholesterol carried in low-density lipoprotein particles. LDL delivers cholesterol to arteries and is the primary driver of atherosclerotic plaque buildup.',
    whatResultMayMean: {
      high: 'Elevated LDL is the primary modifiable risk factor for atherosclerotic cardiovascular disease. Higher LDL means greater plaque accumulation in arteries over time, increasing heart attack and stroke risk.',
      low: 'Very low LDL (below 40 mg/dL) is uncommon outside of medication use. Extremely low levels may rarely be associated with hemorrhagic stroke risk, though the data are not conclusive.',
    },
    commonNonDangerousReasons: {
      high: [
        'Diet high in saturated fats',
        'Genetic predisposition (familial hypercholesterolemia)',
        'Hypothyroidism',
        'Obesity',
        'Sedentary lifestyle',
        'Nephrotic syndrome',
      ],
      low: [
        'Statin therapy (expected effect)',
        'Hyperthyroidism',
        'Low-fat diet',
        'Malabsorption',
      ],
    },
    whenItMatters: 'LDL is the primary target of lipid-lowering therapy and the most important lipid marker for cardiovascular risk assessment. Target levels depend on individual risk factors.',
    dailyLifeActions: {
      high: [
        'Reduce saturated fat to less than 7% of total calories',
        'Eliminate trans fats completely',
        'Increase soluble fiber (oats, barley, beans, lentils) — 5-10 g/day can lower LDL 3-5%',
        'Add plant stanols/sterols (2 g/day)',
        'Eat fatty fish twice per week (salmon, mackerel, sardines)',
        'Exercise regularly — at least 150 minutes of moderate activity per week',
        'Include nuts (almonds, walnuts) in moderation',
        'Maintain a healthy weight',
      ],
      low: [
        'If on statin therapy with very low LDL, discuss target with your clinician',
        'Ensure adequate nutrition',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician for any LDL above 130 mg/dL for a comprehensive cardiovascular risk assessment. Statin therapy is generally recommended for LDL above 190 mg/dL regardless of other risk factors.',
      low: 'Discuss with your clinician if LDL is below 40 mg/dL to ensure this is appropriate for your situation.',
    },
    preAnalyticalConfounders: [
      'Non-fasting state (LDL calculated by Friedewald equation requires fasting; direct LDL does not)',
      'Very high triglycerides (>400 mg/dL) make Friedewald LDL calculation unreliable',
      'Acute illness or surgery (LDL drops for weeks after an acute event)',
      'Posture and tourniquet time',
    ],
    medicationsAffecting: [
      'Statins (decrease 30-50%+)',
      'Ezetimibe (decrease 15-20%)',
      'PCSK9 inhibitors (decrease 50-60%)',
      'Bile acid sequestrants (decrease 15-25%)',
      'Thiazide diuretics (may slightly increase)',
      'Cyclosporine (increase)',
      'Corticosteroids (increase)',
    ],
    relatedBiomarkers: ['TC', 'HDL', 'TRIG', 'NON_HDL'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'HDL',
    name: 'HDL Cholesterol',
    aliases: ['HDL-C', 'high-density lipoprotein cholesterol', 'good cholesterol'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'male', min: 40, max: null, unit: 'mg/dL', source: 'AHA/ACC 2018' },
      { sex: 'female', min: 50, max: null, unit: 'mg/dL', source: 'AHA/ACC 2018' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 30, unit: 'mg/dL', severity: 'warning', message: 'Very low HDL — significantly increased cardiovascular risk.', action: 'Discuss cardiovascular risk reduction strategies with your clinician.' },
    ],
    whatItMeasures: 'The concentration of cholesterol carried in high-density lipoprotein particles. HDL transports cholesterol away from artery walls back to the liver for disposal ("reverse cholesterol transport"), which is protective against cardiovascular disease.',
    whatResultMayMean: {
      high: 'Higher HDL is generally protective. However, extremely high HDL (>100 mg/dL) may not confer additional benefit and in rare genetic variants may even be associated with increased risk.',
      low: 'Low HDL increases cardiovascular risk independently of LDL levels. It is commonly associated with metabolic syndrome, insulin resistance, smoking, and sedentary lifestyle.',
    },
    commonNonDangerousReasons: {
      high: ['Regular vigorous exercise', 'Moderate alcohol consumption', 'Genetic factors', 'Estrogen effects (higher in women)'],
      low: ['Sedentary lifestyle', 'Smoking', 'Obesity and metabolic syndrome', 'High-carbohydrate diet', 'Androgenic medications'],
    },
    whenItMatters: 'HDL is an important component of cardiovascular risk assessment. While low HDL increases risk, pharmacologically raising HDL has not been shown to reduce cardiovascular events, so lifestyle measures are the primary approach.',
    dailyLifeActions: {
      high: ['Continue healthy habits — exercise, balanced diet'],
      low: [
        'Exercise regularly — aerobic exercise is the most effective way to raise HDL',
        'If you smoke, quit — smoking cessation can raise HDL by 5-10%',
        'Lose excess weight — every 6 pounds lost may raise HDL by 1 mg/dL',
        'Choose healthy fats (olive oil, nuts, avocado) over refined carbohydrates',
        'Moderate alcohol intake may raise HDL, but this is not a medical recommendation to start drinking',
        'Reduce refined carbohydrate and sugar intake',
      ],
    },
    whenToSeeDoctor: {
      high: 'Very high HDL (>100 mg/dL) does not typically require follow-up but may warrant discussion if family history of cardiovascular disease is present.',
      low: 'See a clinician if HDL is below 40 mg/dL in men or below 50 mg/dL in women for a comprehensive cardiovascular risk assessment.',
    },
    preAnalyticalConfounders: [
      'Fasting vs. non-fasting (HDL is minimally affected)',
      'Acute illness or surgery (drops for weeks)',
      'Posture during blood draw',
      'Alcohol consumption patterns',
    ],
    medicationsAffecting: [
      'Statins (modest increase of 5-10%)',
      'Niacin (increases HDL 15-30%, but clinical benefit uncertain)',
      'Fibrates (increase)',
      'Thiazide diuretics (may decrease)',
      'Beta-blockers (may decrease)',
      'Androgens/anabolic steroids (decrease)',
      'Oral contraceptives (may increase or decrease depending on formulation)',
    ],
    relatedBiomarkers: ['TC', 'LDL', 'TRIG', 'NON_HDL'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'TRIG',
    name: 'Triglycerides',
    aliases: ['TG', 'triacylglycerols', 'triglyceride'],
    category: 'lipid',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: null, max: 150, unit: 'mg/dL', source: 'AHA/ACC 2018 (fasting)' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 500, unit: 'mg/dL', severity: 'critical', message: 'Very high triglycerides — risk of acute pancreatitis.', action: 'Seek urgent medical evaluation. Strict dietary fat restriction needed.' },
      { direction: 'high', value: 200, unit: 'mg/dL', severity: 'warning', message: 'Elevated triglycerides — increased cardiovascular and pancreatitis risk.', action: 'Discuss dietary changes and management with your clinician.' },
    ],
    whatItMeasures: 'The level of triglycerides, the most common type of fat in the blood. Triglycerides store unused calories and provide energy between meals. They are transported in VLDL and chylomicrons.',
    whatResultMayMean: {
      high: 'Elevated triglycerides are closely linked to metabolic syndrome, insulin resistance, obesity, and excess alcohol or sugar intake. Very high levels (>500 mg/dL) carry a risk of acute pancreatitis.',
      low: 'Low triglycerides are generally favorable and not a concern.',
    },
    commonNonDangerousReasons: {
      high: [
        'Non-fasting blood draw (most common cause of mild elevation)',
        'High-carbohydrate or high-sugar diet',
        'Excess alcohol consumption',
        'Obesity and metabolic syndrome',
        'Hypothyroidism',
        'Pregnancy (physiologic increase)',
      ],
      low: [
        'Low-fat diet',
        'Malabsorption syndromes',
        'Hyperthyroidism',
      ],
    },
    whenItMatters: 'Triglycerides are important for cardiovascular risk assessment (especially as part of metabolic syndrome), for pancreatitis risk evaluation, and for accurate LDL calculation.',
    dailyLifeActions: {
      high: [
        'Reduce sugar and refined carbohydrate intake — this is the single most effective dietary change',
        'Limit alcohol consumption, which strongly raises triglycerides',
        'Increase omega-3 fatty acids from fatty fish (salmon, sardines, mackerel)',
        'Replace saturated fats with unsaturated fats',
        'Lose excess weight — even 5-10% weight loss can lower triglycerides 20%',
        'Exercise regularly — both aerobic and resistance training help',
        'Limit fruit juice and sweetened beverages',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if fasting triglycerides are above 200 mg/dL. Seek urgent evaluation if above 500 mg/dL due to pancreatitis risk.',
      low: 'Low triglycerides do not require follow-up.',
    },
    preAnalyticalConfounders: [
      'Non-fasting state (triglycerides can rise 20-30% after meals; fasting 9-12 hours is recommended)',
      'Alcohol consumed within 24 hours (significant increase)',
      'Recent high-carbohydrate meal',
      'Time of day (lower in the morning)',
      'Glycerol in IV fluids (interferes with assay)',
    ],
    medicationsAffecting: [
      'Fibrates (decrease 30-50%)',
      'Omega-3 fatty acid supplements (decrease)',
      'Statins (modest decrease)',
      'Niacin (decrease)',
      'Corticosteroids (increase)',
      'Oral estrogens (increase)',
      'Beta-blockers (increase)',
      'Thiazide diuretics (increase)',
      'Atypical antipsychotics such as olanzapine (increase)',
      'Isotretinoin/Accutane (increase)',
    ],
    relatedBiomarkers: ['TC', 'LDL', 'HDL', 'NON_HDL', 'GLU', 'HBA1C'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'NON_HDL',
    name: 'Non-HDL Cholesterol',
    aliases: ['non-HDL-C', 'non-HDL cholesterol'],
    category: 'lipid',
    specimenType: 'calculated (total cholesterol minus HDL)',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['mmol/L'],
    referenceRanges: [
      { sex: 'any', min: null, max: 130, unit: 'mg/dL', source: 'AHA/ACC 2018 (optimal for average-risk adults)' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 220, unit: 'mg/dL', severity: 'critical', message: 'Very high non-HDL cholesterol — major cardiovascular risk factor.', action: 'Discuss aggressive lipid-lowering therapy with your clinician.' },
      { direction: 'high', value: 160, unit: 'mg/dL', severity: 'warning', message: 'Elevated non-HDL cholesterol — increased cardiovascular risk.', action: 'Discuss management options with your clinician.' },
    ],
    whatItMeasures: 'All the cholesterol carried in atherogenic (plaque-forming) lipoprotein particles — including LDL, VLDL, IDL, and lipoprotein(a). It is calculated simply as total cholesterol minus HDL. It captures cardiovascular risk better than LDL alone, especially when triglycerides are elevated.',
    whatResultMayMean: {
      high: 'Elevated non-HDL cholesterol indicates a high burden of atherogenic particles and increased risk of cardiovascular disease. It is especially informative when triglycerides are elevated, as it captures VLDL cholesterol that LDL calculation misses.',
      low: 'Low non-HDL cholesterol indicates low atherogenic lipoprotein burden, which is generally favorable.',
    },
    commonNonDangerousReasons: {
      high: ['Same factors that elevate LDL and triglycerides — poor diet, obesity, sedentary lifestyle, genetics'],
      low: ['Statin therapy', 'Very low-fat diet', 'Hyperthyroidism'],
    },
    whenItMatters: 'Non-HDL cholesterol is increasingly recommended as a secondary target alongside LDL, particularly for patients with elevated triglycerides, diabetes, or metabolic syndrome. It does not require fasting.',
    dailyLifeActions: {
      high: [
        'Follow the same dietary and lifestyle recommendations as for elevated LDL and triglycerides',
        'Focus on reducing both saturated fat and refined carbohydrates',
        'Regular aerobic exercise',
        'Weight management',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if non-HDL cholesterol is above 160 mg/dL for cardiovascular risk assessment and treatment discussion.',
      low: 'Low non-HDL cholesterol does not require follow-up.',
    },
    preAnalyticalConfounders: [
      'Does not require fasting (advantage over LDL)',
      'Acute illness can lower values',
      'Posture during blood draw',
    ],
    medicationsAffecting: [
      'Statins (decrease)',
      'Fibrates (decrease, primarily triglyceride component)',
      'PCSK9 inhibitors (decrease)',
      'Same medications affecting total cholesterol and HDL apply',
    ],
    relatedBiomarkers: ['TC', 'LDL', 'HDL', 'TRIG'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
];
