import type { BiomarkerKnowledge } from './types';

export const liverBiomarkers: BiomarkerKnowledge[] = [
  {
    code: 'AST',
    name: 'Aspartate Aminotransferase',
    aliases: ['SGOT', 'aspartate transaminase', 'GOT'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'U/L',
    alternativeUnits: ['IU/L'],
    referenceRanges: [
      { sex: 'male', min: 10, max: 40, unit: 'U/L', source: 'ACG 2017' },
      { sex: 'female', min: 9, max: 32, unit: 'U/L', source: 'ACG 2017' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 1000, unit: 'U/L', severity: 'critical', message: 'Massively elevated AST — may indicate acute hepatitis, ischemic liver injury, or drug-induced liver injury.', action: 'Seek emergency medical evaluation.' },
      { direction: 'high', value: 200, unit: 'U/L', severity: 'warning', message: 'Significantly elevated AST warrants prompt investigation.', action: 'See your clinician for liver evaluation.' },
    ],
    whatItMeasures: 'An enzyme found in the liver, heart, muscle, kidneys, and brain. When cells in these organs are damaged, AST leaks into the bloodstream. AST is less specific to the liver than ALT.',
    whatResultMayMean: {
      high: 'Elevated AST may indicate liver disease (hepatitis, fatty liver, cirrhosis), muscle damage (rhabdomyolysis, intense exercise), heart attack, or hemolysis. The AST:ALT ratio helps determine the cause.',
      low: 'Low AST is generally not clinically significant. Very low levels may occasionally be seen with B6 deficiency or chronic dialysis.',
    },
    commonNonDangerousReasons: {
      high: [
        'Intense exercise or muscle injury (AST is present in muscle)',
        'Non-alcoholic fatty liver disease (NAFLD)',
        'Moderate alcohol consumption',
        'Medications such as statins (mild elevation)',
        'Hemolysis in the sample (lab artifact)',
      ],
      low: [],
    },
    whenItMatters: 'AST is part of the standard liver panel and is important for detecting and monitoring liver disease. The AST:ALT ratio above 2:1 is suggestive of alcoholic liver disease.',
    dailyLifeActions: {
      high: [
        'Limit or eliminate alcohol consumption',
        'Maintain a healthy weight — weight loss can improve fatty liver',
        'Avoid unnecessary over-the-counter medications that stress the liver (e.g., excessive acetaminophen)',
        'Stay hydrated and eat a balanced diet rich in vegetables and lean proteins',
        'Allow recovery time after intense exercise before retesting',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if AST is above 2x the upper limit of normal (above 80 U/L). Seek urgent evaluation if above 500 U/L or with jaundice, dark urine, or abdominal pain.',
      low: 'Low AST does not typically require follow-up.',
    },
    preAnalyticalConfounders: [
      'Intense exercise within 24-48 hours (muscle-derived AST)',
      'Hemolysis in the sample (falsely elevated)',
      'Intramuscular injection (minor increase)',
    ],
    medicationsAffecting: [
      'Statins (mild to moderate increase)',
      'Acetaminophen/paracetamol in excess (significant increase)',
      'Isoniazid (increase — hepatotoxic)',
      'Anti-seizure medications such as valproic acid (increase)',
      'Herbal supplements (kava, comfrey — hepatotoxic)',
      'Amiodarone (increase)',
    ],
    relatedBiomarkers: ['ALT', 'ALP', 'GGT', 'TBIL', 'DBIL', 'ALB'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'ALT',
    name: 'Alanine Aminotransferase',
    aliases: ['SGPT', 'alanine transaminase', 'GPT'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'U/L',
    alternativeUnits: ['IU/L'],
    referenceRanges: [
      { sex: 'male', min: 7, max: 56, unit: 'U/L', source: 'ACG 2017' },
      { sex: 'female', min: 7, max: 45, unit: 'U/L', source: 'ACG 2017' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 1000, unit: 'U/L', severity: 'critical', message: 'Massively elevated ALT — indicates acute liver injury. Possible viral hepatitis, drug toxicity, or ischemia.', action: 'Seek emergency medical evaluation.' },
      { direction: 'high', value: 200, unit: 'U/L', severity: 'warning', message: 'Significantly elevated ALT — liver injury should be investigated.', action: 'See your clinician promptly.' },
    ],
    whatItMeasures: 'An enzyme found predominantly in the liver. ALT is more specific to the liver than AST. When liver cells are damaged or inflamed, ALT leaks into the bloodstream.',
    whatResultMayMean: {
      high: 'Elevated ALT most commonly indicates liver cell damage. Causes include non-alcoholic fatty liver disease (the most common cause of mild elevation), alcoholic liver disease, viral hepatitis, drug-induced liver injury, and autoimmune hepatitis.',
      low: 'Low ALT is generally not clinically significant.',
    },
    commonNonDangerousReasons: {
      high: [
        'Non-alcoholic fatty liver disease (NAFLD/MAFLD)',
        'Alcohol consumption',
        'Medications (statins, acetaminophen)',
        'Obesity and metabolic syndrome',
        'Strenuous exercise (less than AST, but possible)',
      ],
      low: [],
    },
    whenItMatters: 'ALT is the most liver-specific transaminase and the best initial marker for hepatocellular injury. It is used for screening, diagnosis, and monitoring of liver diseases.',
    dailyLifeActions: {
      high: [
        'Reduce or eliminate alcohol consumption',
        'Lose weight if overweight — even 5-10% body weight reduction can significantly improve fatty liver',
        'Limit sugar and refined carbohydrates, which contribute to fatty liver',
        'Exercise regularly — both aerobic and resistance training can reduce liver fat',
        'Review all medications and supplements with your clinician',
        'Limit acetaminophen to under 2 grams per day',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if ALT is persistently above the upper limit of normal on repeat testing. Seek urgent evaluation if above 300 U/L or with symptoms such as jaundice, abdominal pain, or dark urine.',
      low: 'Low ALT does not typically require follow-up.',
    },
    preAnalyticalConfounders: [
      'Intense exercise (less effect than on AST)',
      'Body mass index (ALT tends to be higher in obese individuals)',
      'Hemolysis (minor artifact)',
      'Diurnal variation (higher in the afternoon)',
    ],
    medicationsAffecting: [
      'Acetaminophen/paracetamol (increase, especially in overdose)',
      'Statins (mild increase, generally benign)',
      'NSAIDs (occasional increase)',
      'Anti-tuberculosis drugs — isoniazid, rifampin (increase)',
      'Anticonvulsants — phenytoin, valproic acid (increase)',
      'Some herbal supplements and weight-loss products',
    ],
    relatedBiomarkers: ['AST', 'ALP', 'GGT', 'TBIL', 'DBIL', 'ALB'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'ALP',
    name: 'Alkaline Phosphatase',
    aliases: ['alk phos', 'alkaline phosphatase'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'U/L',
    alternativeUnits: ['IU/L'],
    referenceRanges: [
      { sex: 'any', min: 44, max: 147, unit: 'U/L', source: 'CLSI', pregnancyCaveat: 'ALP is significantly elevated during the third trimester of pregnancy due to placental production. This is physiologically normal.' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 500, unit: 'U/L', severity: 'critical', message: 'Markedly elevated ALP may indicate biliary obstruction, bone disease, or metastatic cancer.', action: 'Seek prompt medical evaluation with imaging.' },
      { direction: 'high', value: 300, unit: 'U/L', severity: 'warning', message: 'Significantly elevated ALP warrants investigation for biliary or bone pathology.', action: 'Discuss with your clinician for further evaluation with GGT and imaging.' },
    ],
    whatItMeasures: 'An enzyme found in the liver (bile ducts), bone, kidneys, intestine, and placenta. Elevated ALP in adults usually comes from the liver or bone. GGT helps determine whether the source is hepatic.',
    whatResultMayMean: {
      high: 'Elevated ALP may indicate bile duct obstruction (stones, stricture, tumor), cholestatic liver disease, bone disease (Paget disease, fracture healing, bone metastases), or pregnancy.',
      low: 'Low ALP may be seen in hypothyroidism, zinc deficiency, malnutrition, or the rare genetic condition hypophosphatasia.',
    },
    commonNonDangerousReasons: {
      high: [
        'Pregnancy (third trimester — placental ALP)',
        'Adolescent growth spurt (bone isoenzyme)',
        'Healing bone fracture',
        'Mild vitamin D deficiency stimulating bone turnover',
        'Blood type B or O (intestinal isoenzyme elevated after fatty meals)',
      ],
      low: [
        'Hypothyroidism',
        'Zinc deficiency',
        'Post-menopausal women on hormone replacement',
      ],
    },
    whenItMatters: 'ALP is a key marker in the cholestatic liver panel (along with GGT and bilirubin) and for bone disease evaluation. An elevated ALP with normal GGT points to bone origin.',
    dailyLifeActions: {
      high: [
        'If related to vitamin D deficiency, discuss supplementation with your clinician',
        'Limit alcohol to reduce liver stress',
        'Ensure adequate calcium and vitamin D for bone health',
      ],
      low: [
        'Ensure adequate zinc intake from foods such as meat, seeds, and legumes',
        'Have thyroid function checked if not recently done',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if ALP is above 1.5x the upper limit of normal, particularly with elevated GGT (suggesting liver origin) or bone pain.',
      low: 'See a clinician if ALP is below 30 U/L, as this may indicate hypophosphatasia or nutritional deficiency.',
    },
    preAnalyticalConfounders: [
      'Recent fatty meal (may raise intestinal ALP, especially in blood types B and O)',
      'Fasting vs. fed state',
      'Pregnancy (physiologic increase)',
      'Age (higher in growing children and adolescents)',
    ],
    medicationsAffecting: [
      'Anticonvulsants such as phenytoin and carbamazepine (increase — enzyme induction)',
      'Antibiotics (rare hepatotoxic increase)',
      'Bisphosphonates (may decrease bone ALP over time)',
      'Oral contraceptives (may slightly decrease)',
    ],
    relatedBiomarkers: ['GGT', 'TBIL', 'DBIL', 'AST', 'ALT', 'ALB'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'GGT',
    name: 'Gamma-Glutamyl Transferase',
    aliases: ['gamma-GT', 'GGT', 'gamma-glutamyl transpeptidase', 'GGTP'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'U/L',
    alternativeUnits: ['IU/L'],
    referenceRanges: [
      { sex: 'male', min: 0, max: 65, unit: 'U/L', source: 'CLSI' },
      { sex: 'female', min: 0, max: 45, unit: 'U/L', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 500, unit: 'U/L', severity: 'critical', message: 'Markedly elevated GGT strongly suggests biliary obstruction or severe liver disease.', action: 'Seek prompt medical evaluation.' },
      { direction: 'high', value: 200, unit: 'U/L', severity: 'warning', message: 'Significantly elevated GGT — investigate for liver or biliary disease.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'An enzyme found primarily in liver cells and bile duct cells. GGT is highly sensitive to liver and biliary tract disease and to alcohol use, but it lacks specificity — it can be elevated by many causes.',
    whatResultMayMean: {
      high: 'Elevated GGT may indicate alcohol use, bile duct disease, fatty liver, medications (enzyme inducers), pancreatic disease, or heart failure. When elevated alongside ALP, it confirms the ALP is of hepatic rather than bone origin.',
      low: 'Low GGT is normal and not clinically significant.',
    },
    commonNonDangerousReasons: {
      high: [
        'Alcohol consumption (even moderate amounts)',
        'Medications that induce liver enzymes (phenytoin, barbiturates)',
        'Obesity and fatty liver',
        'Metabolic syndrome',
        'Older age',
      ],
      low: [],
    },
    whenItMatters: 'GGT is most useful for confirming the hepatic origin of an elevated ALP and as a sensitive (though nonspecific) marker of alcohol use and biliary disease.',
    dailyLifeActions: {
      high: [
        'Reduce or eliminate alcohol consumption — GGT is very sensitive to alcohol',
        'Maintain a healthy weight',
        'Reduce processed foods and excess sugar',
        'Review all medications and supplements with your clinician',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if GGT is above 2x the upper limit of normal, especially with elevated ALP or bilirubin.',
      low: 'Low GGT does not require follow-up.',
    },
    preAnalyticalConfounders: [
      'Alcohol consumption (even moderate; effect lasts days to weeks)',
      'BMI (higher in obesity)',
      'Medications that induce hepatic enzymes',
    ],
    medicationsAffecting: [
      'Alcohol (increase)',
      'Phenytoin, barbiturates, carbamazepine (increase — enzyme induction)',
      'Acetaminophen (increase in excess)',
      'Oral contraceptives (may slightly increase)',
      'Statins (rare mild increase)',
    ],
    relatedBiomarkers: ['ALP', 'ALT', 'AST', 'TBIL', 'DBIL'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'TBIL',
    name: 'Total Bilirubin',
    aliases: ['bilirubin', 'total bili', 'T-Bil'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['µmol/L'],
    referenceRanges: [
      { sex: 'any', min: 0.1, max: 1.2, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 5.0, unit: 'mg/dL', severity: 'critical', message: 'Significantly elevated bilirubin — visible jaundice likely present. May indicate severe liver disease, bile duct obstruction, or hemolysis.', action: 'Seek urgent medical evaluation.' },
      { direction: 'high', value: 2.5, unit: 'mg/dL', severity: 'warning', message: 'Elevated bilirubin — jaundice may be noticeable. Investigate for liver, biliary, or hemolytic causes.', action: 'See your clinician for evaluation.' },
    ],
    whatItMeasures: 'The total amount of bilirubin in your blood, which includes unconjugated (indirect) and conjugated (direct) bilirubin. Bilirubin is a yellow pigment produced during the normal breakdown of red blood cells.',
    whatResultMayMean: {
      high: 'Elevated total bilirubin causes jaundice (yellowing of skin and eyes). Causes include liver disease (hepatitis, cirrhosis), bile duct obstruction (gallstones, tumor), hemolytic anemia, or Gilbert syndrome (a common benign genetic variant).',
      low: 'Low bilirubin is not clinically significant.',
    },
    commonNonDangerousReasons: {
      high: [
        'Gilbert syndrome (affects 5-10% of the population — mild unconjugated hyperbilirubinemia, usually under 3 mg/dL, worsened by fasting or stress)',
        'Fasting or caloric restriction',
        'Intense exercise',
        'Mild dehydration',
      ],
      low: [],
    },
    whenItMatters: 'Bilirubin is essential for evaluating jaundice, monitoring liver disease severity, and assessing for hemolytic conditions. Direct vs. indirect fractionation helps determine the cause.',
    dailyLifeActions: {
      high: [
        'If Gilbert syndrome is diagnosed, no treatment is needed — it is benign',
        'Stay well-hydrated and avoid prolonged fasting',
        'Limit alcohol consumption',
        'Avoid hepatotoxic substances',
      ],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if total bilirubin is above 1.5 mg/dL and you are not known to have Gilbert syndrome. Seek urgent evaluation if above 3 mg/dL or with jaundice, dark urine, pale stools, or abdominal pain.',
      low: 'Low bilirubin does not require follow-up.',
    },
    preAnalyticalConfounders: [
      'Fasting (increases unconjugated bilirubin, especially in Gilbert syndrome)',
      'Exposure to light (bilirubin is photosensitive — sample should be protected from light)',
      'Hemolysis in the sample (falsely elevated)',
      'Prolonged tourniquet application',
    ],
    medicationsAffecting: [
      'Atazanavir and indinavir (increase unconjugated bilirubin — UGT1A1 inhibition)',
      'Rifampin (may interfere with bilirubin uptake)',
      'Phenobarbital (decrease — enzyme induction)',
      'Acetaminophen overdose (increase due to liver injury)',
    ],
    relatedBiomarkers: ['DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'ALB', 'HGB'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'DBIL',
    name: 'Direct Bilirubin',
    aliases: ['conjugated bilirubin', 'direct bili', 'D-Bil'],
    category: 'liver',
    specimenType: 'serum',
    defaultUnit: 'mg/dL',
    alternativeUnits: ['µmol/L'],
    referenceRanges: [
      { sex: 'any', min: 0.0, max: 0.3, unit: 'mg/dL', source: 'CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 2.0, unit: 'mg/dL', severity: 'critical', message: 'Significantly elevated direct bilirubin indicates cholestasis (impaired bile flow) — likely biliary obstruction or severe liver disease.', action: 'Seek urgent medical evaluation with imaging.' },
      { direction: 'high', value: 0.5, unit: 'mg/dL', severity: 'warning', message: 'Elevated direct bilirubin suggests cholestatic liver disease or biliary obstruction.', action: 'Discuss with your clinician.' },
    ],
    whatItMeasures: 'The conjugated (water-soluble) form of bilirubin that has been processed by the liver and is ready for excretion into bile. Elevated direct bilirubin specifically indicates a problem with bile excretion.',
    whatResultMayMean: {
      high: 'Elevated direct bilirubin indicates cholestasis — the bile cannot flow properly from the liver. Causes include gallstones blocking the bile duct, tumors (pancreatic, bile duct), primary biliary cholangitis, or drug-induced cholestasis.',
      low: 'Low direct bilirubin is normal.',
    },
    commonNonDangerousReasons: {
      high: ['Rarely elevated without a significant underlying cause'],
      low: [],
    },
    whenItMatters: 'Direct bilirubin helps distinguish conjugated (liver/biliary) from unconjugated (hemolysis/Gilbert) hyperbilirubinemia. It is critical for evaluating obstructive jaundice.',
    dailyLifeActions: {
      high: ['Follow your clinician\'s recommendations for imaging and further workup', 'Avoid alcohol and hepatotoxic substances'],
      low: [],
    },
    whenToSeeDoctor: {
      high: 'See a clinician promptly if direct bilirubin is elevated, as it usually indicates a condition requiring medical investigation. Seek urgent care with jaundice, fever, or abdominal pain.',
      low: 'Low direct bilirubin does not require follow-up.',
    },
    preAnalyticalConfounders: [
      'Light exposure of sample (bilirubin degradation)',
      'Hemolysis (may interfere with the assay)',
    ],
    medicationsAffecting: [
      'Oral contraceptives (may cause cholestasis)',
      'Anabolic steroids (cholestatic pattern)',
      'Erythromycin and amoxicillin-clavulanate (drug-induced cholestasis)',
      'Phenothiazines (cholestatic hepatitis)',
    ],
    relatedBiomarkers: ['TBIL', 'ALP', 'GGT', 'ALT', 'AST'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
];
