import type { BiomarkerKnowledge } from './types';

export const vitaminBiomarkers: BiomarkerKnowledge[] = [
  {
    code: 'VITD',
    name: 'Vitamin D (25-Hydroxyvitamin D)',
    aliases: ['25-OH vitamin D', '25-hydroxycholecalciferol', 'calcidiol', 'vitamin D', '25(OH)D'],
    category: 'vitamin',
    specimenType: 'serum',
    defaultUnit: 'ng/mL',
    alternativeUnits: ['nmol/L'],
    referenceRanges: [
      { sex: 'any', min: 30, max: 100, unit: 'ng/mL', source: 'Endocrine Society 2024' },
    ],
    redFlagThresholds: [
      { direction: 'high', value: 150, unit: 'ng/mL', severity: 'critical', message: 'Vitamin D toxicity — risk of hypercalcemia, kidney stones, and organ damage.', action: 'Stop all vitamin D supplements and seek medical evaluation urgently.' },
      { direction: 'low', value: 10, unit: 'ng/mL', severity: 'warning', message: 'Severe vitamin D deficiency — risk of osteomalacia (bone softening) and significant bone loss.', action: 'See your clinician for high-dose vitamin D supplementation.' },
    ],
    whatItMeasures: 'The circulating level of 25-hydroxyvitamin D, the main storage form of vitamin D in the body. It reflects combined vitamin D from sun exposure, diet, and supplements. It is the best indicator of overall vitamin D status.',
    whatResultMayMean: {
      high: 'Vitamin D toxicity (usually only from excessive supplementation, not from sun or diet) can cause hypercalcemia, nausea, kidney stones, and in severe cases, kidney failure and cardiac arrhythmias.',
      low: 'Vitamin D deficiency can lead to poor calcium absorption, weakened bones (osteopenia, osteoporosis, osteomalacia), muscle weakness, increased fall risk, and has been associated with immune dysfunction and mood changes.',
    },
    commonNonDangerousReasons: {
      high: ['Over-supplementation with high-dose vitamin D', 'Granulomatous diseases (sarcoidosis) — increased 1,25-OH conversion'],
      low: [
        'Limited sun exposure (northern latitudes, winter, indoor lifestyle)',
        'Dark skin pigmentation (reduces UV synthesis)',
        'Sunscreen use',
        'Obesity (vitamin D is sequestered in fat tissue)',
        'Older age (reduced skin synthesis capacity)',
        'Low dietary intake (few natural food sources)',
        'Malabsorption conditions (celiac disease, IBD)',
      ],
    },
    whenItMatters: 'Vitamin D is important for bone health, calcium metabolism, immune function, and muscle strength. Testing is particularly important in people at risk of deficiency and in those with osteoporosis, recurrent fractures, or unexplained bone pain.',
    dailyLifeActions: {
      high: [
        'Stop all vitamin D supplements immediately and see your clinician',
        'Reduce calcium-rich food intake until levels normalize',
        'Stay well-hydrated',
      ],
      low: [
        'Consider vitamin D3 (cholecalciferol) supplementation — 1,000-2,000 IU/day is a common maintenance dose for mild deficiency',
        'For moderate-to-severe deficiency, higher doses (e.g., 5,000 IU/day or 50,000 IU/week) may be prescribed by your clinician',
        'Get 10-30 minutes of midday sun exposure several times per week (without burning)',
        'Include vitamin D-rich foods: fatty fish (salmon, sardines, mackerel), fortified milk and cereals, egg yolks, cod liver oil',
        'Take vitamin D with a meal containing fat to enhance absorption',
      ],
    },
    whenToSeeDoctor: {
      high: 'See a clinician if vitamin D is above 80 ng/mL, and urgently if above 100 ng/mL, especially with symptoms such as nausea, excessive thirst, or confusion.',
      low: 'See a clinician if vitamin D is below 20 ng/mL for supplementation guidance. See promptly if below 10 ng/mL.',
    },
    preAnalyticalConfounders: [
      'Season and latitude (lower in winter at higher latitudes)',
      'Time since last sun exposure or supplement dose',
      'BMI (vitamin D sequestered in fat — levels may appear lower in obese individuals)',
      'Assay variability between laboratories',
    ],
    medicationsAffecting: [
      'Vitamin D supplements (increase)',
      'Anticonvulsants — phenytoin, carbamazepine (decrease via increased catabolism)',
      'Glucocorticoids (decrease via increased catabolism)',
      'Cholestyramine (decrease via impaired absorption)',
      'Rifampin (decrease via increased metabolism)',
      'Orlistat (may decrease via fat malabsorption)',
      'Ketoconazole (inhibits 1-alpha-hydroxylase)',
    ],
    relatedBiomarkers: ['CA', 'PHOS', 'ALP', 'PTH (if available)'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'B12',
    name: 'Vitamin B12',
    aliases: ['cobalamin', 'cyanocobalamin', 'B12', 'vitamin B-12'],
    category: 'vitamin',
    specimenType: 'serum',
    defaultUnit: 'pg/mL',
    alternativeUnits: ['pmol/L', 'ng/L'],
    referenceRanges: [
      { sex: 'any', min: 200, max: 900, unit: 'pg/mL', source: 'CLSI/WHO' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 150, unit: 'pg/mL', severity: 'critical', message: 'Severe B12 deficiency — risk of irreversible neurological damage if untreated.', action: 'See your clinician urgently for B12 injections.' },
      { direction: 'low', value: 300, unit: 'pg/mL', severity: 'warning', message: 'Low-normal B12 — may indicate early or subclinical deficiency, especially with symptoms.', action: 'Discuss methylmalonic acid and homocysteine testing with your clinician for confirmation.' },
    ],
    whatItMeasures: 'The level of vitamin B12 (cobalamin) in the blood. B12 is essential for DNA synthesis, red blood cell production, and nervous system function. It is obtained from animal products and requires intrinsic factor for absorption in the gut.',
    whatResultMayMean: {
      high: 'Very high B12 levels (>1,000 pg/mL) may be seen with supplements, liver disease, myeloproliferative disorders, or kidney disease. B12 toxicity from supplements is extremely rare, as excess is excreted.',
      low: 'B12 deficiency causes macrocytic anemia and neurological problems (peripheral neuropathy, cognitive decline, balance issues). If left untreated, neurological damage may become permanent. Common causes include pernicious anemia, vegan diet, malabsorption, and metformin use.',
    },
    commonNonDangerousReasons: {
      high: ['B12 supplementation (oral or injections)', 'Liver disease (B12 stored in liver is released)', 'High intake of fortified foods'],
      low: [
        'Vegan or strict vegetarian diet (no animal product intake)',
        'Long-term metformin use',
        'Pernicious anemia (autoimmune destruction of intrinsic factor)',
        'Older age (reduced absorption)',
        'Proton pump inhibitor (PPI) use',
        'Celiac disease or Crohn disease (malabsorption)',
        'Chronic alcohol use',
      ],
    },
    whenItMatters: 'B12 testing is important for evaluating macrocytic anemia, peripheral neuropathy, cognitive changes, and fatigue — especially in vegans, older adults, and patients on metformin or PPIs.',
    dailyLifeActions: {
      high: ['Very high B12 from supplements is generally harmless, but discuss with your clinician if you are not supplementing'],
      low: [
        'If vegan or vegetarian, take a B12 supplement (at least 250 µg daily or 1,000 µg 2-3 times per week)',
        'Include B12-rich foods: meat, fish, eggs, dairy, fortified plant milks and cereals',
        'If on metformin, discuss B12 monitoring and supplementation with your clinician',
        'Consider sublingual B12 if you have absorption issues',
        'Nutritional yeast is a good plant-based source of B12 (if fortified)',
      ],
    },
    whenToSeeDoctor: {
      high: 'Discuss with your clinician if B12 is very high (>1,500 pg/mL) without supplementation, to evaluate for liver disease or hematologic conditions.',
      low: 'See a clinician if B12 is below 300 pg/mL with symptoms (fatigue, numbness, tingling, cognitive changes), or urgently if below 150 pg/mL.',
    },
    preAnalyticalConfounders: [
      'Recent B12 injection or high-dose supplement (will be very high)',
      'Biotin supplements (may interfere with some immunoassays)',
      'Oral contraceptives (may lower serum B12 without true deficiency)',
      'Pregnancy (physiologic decrease)',
      'Serum B12 can be normal despite functional deficiency — methylmalonic acid and homocysteine are more sensitive',
    ],
    medicationsAffecting: [
      'B12 supplements/injections (increase)',
      'Metformin (decrease absorption over years)',
      'Proton pump inhibitors — omeprazole, pantoprazole (decrease absorption)',
      'H2 blockers — ranitidine, famotidine (decrease absorption)',
      'Colchicine (decrease absorption)',
      'Nitrous oxide exposure (inactivates B12)',
      'Oral contraceptives (may lower serum levels)',
    ],
    relatedBiomarkers: ['FOLATE', 'MCV', 'HGB', 'RDW'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
  {
    code: 'FOLATE',
    name: 'Folate',
    aliases: ['folic acid', 'vitamin B9', 'serum folate', 'folacin'],
    category: 'vitamin',
    specimenType: 'serum',
    defaultUnit: 'ng/mL',
    alternativeUnits: ['nmol/L'],
    referenceRanges: [
      { sex: 'any', min: 3.0, max: 20.0, unit: 'ng/mL', source: 'WHO/CLSI' },
    ],
    redFlagThresholds: [
      { direction: 'low', value: 2.0, unit: 'ng/mL', severity: 'warning', message: 'Low folate — risk of megaloblastic anemia and, in pregnancy, neural tube defects.', action: 'See your clinician for folate supplementation.' },
    ],
    whatItMeasures: 'The level of folate (vitamin B9) in the blood. Folate is essential for DNA synthesis, cell division, and red blood cell production. It is especially critical during pregnancy for fetal neural tube development.',
    whatResultMayMean: {
      high: 'High serum folate from supplements or fortified foods is generally not harmful. Very high levels may rarely mask B12 deficiency by correcting the anemia while allowing neurological damage to progress — this is why B12 should be checked alongside folate.',
      low: 'Folate deficiency causes megaloblastic anemia (large, immature red cells) and elevated homocysteine. In pregnancy, it increases the risk of neural tube defects. Causes include poor diet, malabsorption, alcoholism, and increased demand (pregnancy, hemolysis).',
    },
    commonNonDangerousReasons: {
      high: ['Folic acid supplementation', 'Fortified foods', 'High vegetable intake'],
      low: [
        'Poor dietary intake (low vegetable and legume consumption)',
        'Alcohol use (impairs folate absorption and storage)',
        'Pregnancy (increased demand)',
        'Celiac disease or other malabsorption conditions',
        'Rapid cell turnover (hemolytic anemia, psoriasis)',
      ],
    },
    whenItMatters: 'Folate is important for evaluating macrocytic anemia (alongside B12), monitoring patients on methotrexate, and ensuring adequacy before and during pregnancy.',
    dailyLifeActions: {
      high: ['No action needed if from diet or appropriate supplementation'],
      low: [
        'Eat folate-rich foods: dark leafy greens (spinach, kale), legumes (lentils, chickpeas), asparagus, broccoli, fortified grains',
        'If planning pregnancy, take 400-800 µg of folic acid daily starting at least one month before conception',
        'Limit alcohol, which depletes folate',
        'Cook vegetables lightly — folate is heat-sensitive',
      ],
    },
    whenToSeeDoctor: {
      high: 'Very high folate from supplements is generally safe but ensure B12 is also adequate.',
      low: 'See a clinician if folate is below 3 ng/mL, especially with macrocytic anemia, fatigue, or if planning pregnancy.',
    },
    preAnalyticalConfounders: [
      'Recent meal rich in folate (serum folate fluctuates with diet)',
      'Hemolysis (red cell folate is much higher than serum — hemolysis falsely elevates)',
      'Serum folate reflects recent intake; red cell folate is a better long-term indicator',
      'Fasting is preferred for more consistent results',
    ],
    medicationsAffecting: [
      'Folic acid supplements (increase)',
      'Methotrexate (folate antagonist — decreases utilization)',
      'Trimethoprim (weak antifolate — may decrease)',
      'Phenytoin and carbamazepine (decrease absorption and increase metabolism)',
      'Sulfasalazine (decreases absorption)',
      'Oral contraceptives (may slightly decrease)',
      'Metformin (may slightly decrease)',
    ],
    relatedBiomarkers: ['B12', 'MCV', 'HGB', 'RDW'],
    evidenceTier: 1,
    lastReviewed: '2026-03-01',
  },
];
